#!/usr/bin/env python3
"""
savia-dual-proxy — Transparent failover proxy between Anthropic API and local Ollama.

Part of Savia Dual (pm-workspace). Listens on 127.0.0.1:8787 by default.
Claude Code talks to this proxy via ANTHROPIC_BASE_URL. The proxy tries the
primary upstream (Anthropic) first; on failure (network, 5xx, 429, timeout)
it transparently falls back to a local Ollama instance speaking the native
Anthropic /v1/messages protocol (Ollama >= 0.20.0).

Zero external dependencies. Stdlib only. Python >= 3.8.

Usage:
    python3 savia-dual-proxy.py [--config PATH] [--host HOST] [--port PORT]

Config file: ~/.savia/dual/config.json (generated by setup-savia-dual.sh),
             or $SAVIA_DUAL_CONFIG when set (the systemd unit sets it).
Log file:    ~/.savia/dual/events.jsonl

Safety contract:
  - Only loopback listen hosts are accepted (exit 2 otherwise).
  - Only POST /v1/messages fails over to Ollama; any other path (batches,
    files, models...) gets the primary's answer, so effectful requests are
    never replayed against another upstream.
  - 4xx from the primary is returned as is: it is the client's error, not an
    outage, and it neither falls back nor counts for the circuit breaker.
  - Credentials (x-api-key, authorization, cookie...) never reach Ollama:
    only an allowlist of protocol headers is forwarded there.
  - Successful responses are relayed as a stream (SSE included). Once the
    first byte is sent there is no failover; a cut stream ends with an SSE
    error event and a "stream_interrupted" entry in events.jsonl.

Exit codes: 0 clean shutdown · 1 cannot bind · 2 invalid config or host.
"""
from __future__ import annotations
import argparse
import http.client
import ipaddress
import json
import logging
import os
import socket
import sys
import threading
import time
import urllib.error
import urllib.parse
import urllib.request
from http.server import BaseHTTPRequestHandler, ThreadingHTTPServer
from pathlib import Path
from typing import Any

DEFAULT_ANTHROPIC_UPSTREAM = os.environ.get(
    "SAVIA_API_UPSTREAM", "https://api.anthropic.com"
)

DEFAULT_CONFIG: dict[str, Any] = {
    "listen_host": "127.0.0.1",
    "listen_port": 8787,
    "anthropic_upstream": DEFAULT_ANTHROPIC_UPSTREAM,
    "ollama_upstream": "http://127.0.0.1:11434",
    "fallback_triggers": {
        "network_error": True,
        "http_5xx": True,
        "http_429": True,
        "timeout_seconds": 30,
    },
    "circuit_breaker": {
        "consecutive_failures": 3,
        "cooldown_seconds": 60,
    },
    "local_model": "gemma4:e4b",
    "log_path": "~/.savia/dual/events.jsonl",
}


# Only these headers travel to the local fallback: no credentials, no cookies.
OLLAMA_HEADER_ALLOWLIST = {
    "content-type", "accept", "anthropic-version", "anthropic-beta", "user-agent",
}
HOP_BY_HOP = {
    "host", "content-length", "connection", "keep-alive",
    "proxy-authenticate", "proxy-authorization", "te", "trailer",
    "transfer-encoding", "upgrade",
}
# Requests that may be replayed against the local model. Anything else is
# answered by the primary alone (it may have side effects upstream).
FALLBACK_ROUTES = {("POST", "/v1/messages")}
STREAM_CHUNK = 65536
SSE_INTERRUPTED = (
    b'event: error\ndata: {"type":"error","error":{"type":"api_error",'
    b'"message":"savia-dual: upstream stream interrupted"}}\n\n'
)
UPSTREAM_ERRORS = (
    urllib.error.URLError, socket.timeout, TimeoutError, ConnectionError,
    http.client.HTTPException, OSError,
)


def is_loopback_host(host: str) -> bool:
    if host == "localhost":
        return True
    try:
        return ipaddress.ip_address(host).is_loopback
    except ValueError:
        return False


class CircuitBreaker:
    """Minimal circuit breaker. After N consecutive failures to primary,
    route directly to fallback for cooldown_seconds before retrying primary."""

    def __init__(self, threshold: int, cooldown: int) -> None:
        self.threshold = threshold
        self.cooldown = cooldown
        self.failures = 0
        self.opened_at: float | None = None
        self._lock = threading.Lock()

    def should_skip_primary(self) -> bool:
        with self._lock:
            if self.opened_at is None:
                return False
            if time.time() - self.opened_at >= self.cooldown:
                self.opened_at = None
                self.failures = 0
                return False
            return True

    def record_success(self) -> None:
        with self._lock:
            self.failures = 0
            self.opened_at = None

    def record_failure(self) -> None:
        with self._lock:
            self.failures += 1
            if self.failures >= self.threshold and self.opened_at is None:
                self.opened_at = time.time()


class DualProxy:
    def __init__(self, config: dict[str, Any]) -> None:
        self.config = config
        self.breaker = CircuitBreaker(
            config["circuit_breaker"]["consecutive_failures"],
            config["circuit_breaker"]["cooldown_seconds"],
        )
        log_path = Path(os.path.expanduser(config["log_path"]))
        log_path.parent.mkdir(parents=True, exist_ok=True)
        self.log_path = log_path
        self._log_lock = threading.Lock()

    def log_event(self, event: dict[str, Any]) -> None:
        event["ts"] = time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime())
        line = json.dumps(event, ensure_ascii=False)
        with self._log_lock:
            try:
                with self.log_path.open("a", encoding="utf-8") as fh:
                    fh.write(line + "\n")
            except OSError as exc:
                # Routing must not stop because the audit log is unwritable,
                # but the loss is reported on stderr instead of hidden.
                logging.warning("events.jsonl not writable (%s): %s", self.log_path, exc)

    def _should_fallback(self, status: int, err: Exception | None) -> str | None:
        triggers = self.config["fallback_triggers"]
        if err is not None:
            if triggers["network_error"]:
                return f"network_error:{type(err).__name__}"
            return None
        if status == 429 and triggers["http_429"]:
            return "http_429"
        if 500 <= status < 600 and triggers["http_5xx"]:
            return f"http_{status}"
        return None

    def _rewrite_for_ollama(self, body_bytes: bytes) -> bytes:
        try:
            body = json.loads(body_bytes.decode("utf-8"))
        except (ValueError, UnicodeDecodeError):
            return body_bytes
        if not isinstance(body, dict):
            return body_bytes
        model = body.get("model", "")
        if model and not model.startswith(("gemma", "llama", "qwen", "mistral", "phi")):
            body["model"] = self.config["local_model"]
        # Ollama ignores unknown fields but strip cache markers to be safe
        body.pop("metadata", None)
        return json.dumps(body).encode("utf-8")

    @staticmethod
    def _headers_for(target: str, headers: dict[str, str]) -> dict[str, str]:
        if target == "ollama":
            return {k: v for k, v in headers.items() if k.lower() in OLLAMA_HEADER_ALLOWLIST}
        return {k: v for k, v in headers.items() if k.lower() not in HOP_BY_HOP}

    def forward(
        self,
        target: str,
        upstream_base: str,
        method: str,
        path: str,
        headers: dict[str, str],
        body: bytes,
        timeout: float,
    ) -> tuple[int, dict[str, str], Any, Exception | None]:
        """Open the upstream request. On 2xx/3xx the third element is the open
        response (to be relayed as a stream); otherwise it is the error body."""
        url = upstream_base.rstrip("/") + path
        req = urllib.request.Request(url, data=body if body else None, method=method)
        for k, v in self._headers_for(target, headers).items():
            req.add_header(k, v)
        try:
            resp = urllib.request.urlopen(req, timeout=timeout)
            return resp.status, dict(resp.getheaders()), resp, None
        except urllib.error.HTTPError as e:
            try:
                data = e.read() or b""
            except UPSTREAM_ERRORS as exc:
                logging.warning("%s error body unreadable: %s", target, type(exc).__name__)
                data = b""
            return e.code, dict(e.headers or {}), data, None
        except UPSTREAM_ERRORS as e:
            return 0, {}, b"", e

    def handle_messages(
        self, method: str, path: str, headers: dict[str, str], body: bytes
    ) -> tuple[int, dict[str, str], Any, dict[str, Any]]:
        """Route one request. Returns (status, headers, body_or_stream, event);
        the caller relays the body and logs the event once delivery ends."""
        start = time.time()
        can_fallback = (method, path.split("?", 1)[0]) in FALLBACK_ROUTES
        skip_primary = can_fallback and self.breaker.should_skip_primary()
        fallback_reason: str | None = "circuit_open"

        if not skip_primary:
            status, resp_headers, payload, err = self.forward(
                target="anthropic",
                upstream_base=self.config["anthropic_upstream"],
                method=method,
                path=path,
                headers=headers,
                body=body,
                timeout=self.config["fallback_triggers"]["timeout_seconds"],
            )
            fallback_reason = self._should_fallback(status, err)
            if fallback_reason is None and err is None:
                # 2xx/3xx, or a 4xx that is the client's own error: either
                # way the primary is healthy and its answer is final.
                self.breaker.record_success()
                return status, resp_headers, payload, {"route": "anthropic", "status": status}
            if err is not None or (500 <= status < 600) or status == 429:
                self.breaker.record_failure()
            if not can_fallback:
                event = {"route": "anthropic", "status": status or 502,
                         "fallback_reason": fallback_reason, "fallback": "not_allowed"}
                if err is not None:
                    return 502, {"Content-Type": "application/json"}, self._error_body(
                        "Primary upstream unavailable and this route has no fallback",
                        fallback_reason, err), event
                return status, resp_headers, payload, event

        ollama_status, ollama_headers, ollama_payload, ollama_err = self.forward(
            target="ollama",
            upstream_base=self.config["ollama_upstream"],
            method=method,
            path=path,
            headers=headers,
            body=self._rewrite_for_ollama(body),
            timeout=120,
        )
        if ollama_err is not None:
            event = {
                "route": "none",
                "status": 503,
                "fallback_reason": fallback_reason,
                "ollama_error": type(ollama_err).__name__,
                "latency_ms": int((time.time() - start) * 1000),
            }
            return 503, {"Content-Type": "application/json"}, self._error_body(
                "Both Anthropic and Ollama are unavailable", fallback_reason, ollama_err), event
        return ollama_status, ollama_headers, ollama_payload, {
            "route": "ollama",
            "status": ollama_status,
            "fallback_reason": fallback_reason,
            "local_model": self.config["local_model"],
        }

    @staticmethod
    def _error_body(message: str, reason: str | None, err: Exception) -> bytes:
        return json.dumps({
            "type": "error",
            "error": {
                "type": "upstream_unavailable",
                "message": message,
                "fallback_reason": reason,
                "upstream_error": type(err).__name__,
            },
        }).encode("utf-8")


class ProxyHandler(BaseHTTPRequestHandler):
    proxy: DualProxy  # injected

    def log_message(self, format: str, *args: Any) -> None:  # quiet stdout
        pass

    def _dispatch(self, method: str) -> None:
        start = time.time()
        raw_length = self.headers.get("Content-Length", "0") or "0"
        try:
            length = int(raw_length)
            if length < 0:
                raise ValueError(raw_length)
        except ValueError:
            self._write(400, {"Content-Type": "application/json"},
                        b'{"error":"invalid_content_length"}')
            return
        body = self.rfile.read(length) if length > 0 else b""
        headers = {k: v for k, v in self.headers.items()}
        path = self.path
        if path == "/health":
            self._write(200, {"Content-Type": "application/json"},
                        json.dumps({"status": "ok"}).encode("utf-8"))
            return
        if not path.startswith("/v1/"):
            self._write(404, {"Content-Type": "application/json"},
                        b'{"error":"not_found"}')
            return
        status, resp_headers, payload, event = self.proxy.handle_messages(
            method, path, headers, body)
        if isinstance(payload, (bytes, bytearray)):
            self._write(status, resp_headers, bytes(payload))
        else:
            event.update(self._relay(status, resp_headers, payload))
        event["latency_ms"] = int((time.time() - start) * 1000)
        self.proxy.log_event(event)

    def _send_head(self, status: int, headers: dict[str, str]) -> None:
        self.send_response(status)
        for k, v in headers.items():
            if k.lower() not in HOP_BY_HOP:
                self.send_header(k, v)

    def _write(self, status: int, headers: dict[str, str], body: bytes) -> None:
        self._send_head(status, headers)
        self.send_header("Content-Length", str(len(body)))
        self.end_headers()
        self.wfile.write(body)

    def _relay(self, status: int, headers: dict[str, str], resp: Any) -> dict[str, Any]:
        """Stream an open upstream response to the client chunk by chunk.
        Close-delimited (HTTP/1.0): no Content-Length, so a cut is visible."""
        is_sse = "text/event-stream" in {k.lower(): v for k, v in headers.items()}.get(
            "content-type", "")
        self._send_head(status, headers)
        self.send_header("Connection", "close")
        self.end_headers()
        self.close_connection = True
        read = getattr(resp, "read1", resp.read)
        outcome: dict[str, Any] = {}
        try:
            while True:
                try:
                    chunk = read(STREAM_CHUNK)
                except UPSTREAM_ERRORS as exc:
                    outcome = {"stream_interrupted": True, "error": type(exc).__name__}
                    if is_sse:
                        self.wfile.write(SSE_INTERRUPTED)
                    break
                if not chunk:
                    # read1() returns b"" (no IncompleteRead) when a body with
                    # Content-Length ends early: the pending length tells.
                    if getattr(resp, "length", None):
                        outcome = {"stream_interrupted": True, "error": "IncompleteRead"}
                        if is_sse:
                            self.wfile.write(SSE_INTERRUPTED)
                    break
                self.wfile.write(chunk)
                self.wfile.flush()
        except (BrokenPipeError, ConnectionResetError) as exc:
            outcome = {"client_disconnected": True, "error": type(exc).__name__}
        finally:
            resp.close()
        return outcome

    def do_GET(self) -> None: self._dispatch("GET")
    def do_POST(self) -> None: self._dispatch("POST")


class ConfigError(Exception):
    pass


def load_config(path: Path) -> dict[str, Any]:
    merged = json.loads(json.dumps(DEFAULT_CONFIG))
    if not path.exists():
        return merged
    try:
        with path.open("r", encoding="utf-8") as fh:
            user = json.load(fh)
    except (OSError, ValueError) as exc:
        raise ConfigError(f"cannot read config {path}: {exc}") from exc
    if not isinstance(user, dict):
        raise ConfigError(f"config {path} must be a JSON object")
    merged.update({k: v for k, v in user.items() if k not in ("fallback_triggers", "circuit_breaker")})
    if isinstance(user.get("fallback_triggers"), dict):
        merged["fallback_triggers"].update(user["fallback_triggers"])
    if isinstance(user.get("circuit_breaker"), dict):
        merged["circuit_breaker"].update(user["circuit_breaker"])
    return merged


def main() -> int:
    parser = argparse.ArgumentParser(description="Savia Dual failover proxy")
    parser.add_argument(
        "--config", default=os.environ.get("SAVIA_DUAL_CONFIG", "~/.savia/dual/config.json"))
    parser.add_argument("--host", default=None)
    parser.add_argument("--port", type=int, default=None)
    args = parser.parse_args()
    logging.basicConfig(level=logging.INFO, format="%(asctime)s %(message)s")
    config_path = Path(os.path.expanduser(args.config))
    try:
        config = load_config(config_path)
    except ConfigError as exc:
        print(f"savia-dual: {exc}", file=sys.stderr)
        return 2
    if args.host is not None:
        config["listen_host"] = args.host
    if args.port is not None:
        config["listen_port"] = args.port
    if not is_loopback_host(str(config["listen_host"])):
        print(f"savia-dual: refusing to listen on {config['listen_host']!r}: "
              "only loopback hosts (127.0.0.1, ::1, localhost) are allowed", file=sys.stderr)
        return 2
    proxy = DualProxy(config)
    ProxyHandler.proxy = proxy
    try:
        server = ThreadingHTTPServer((config["listen_host"], config["listen_port"]), ProxyHandler)
    except OSError as exc:
        print(f"savia-dual: cannot bind {config['listen_host']}:{config['listen_port']}: {exc}",
              file=sys.stderr)
        return 1
    host, port = server.server_address[:2]
    logging.info("savia-dual listening on http://%s:%d", host, port)
    logging.info("primary=%s fallback=%s model=%s",
                 config["anthropic_upstream"], config["ollama_upstream"], config["local_model"])
    try:
        server.serve_forever()
    except KeyboardInterrupt:
        logging.info("shutdown")
    return 0


if __name__ == "__main__":
    sys.exit(main())
