# communication — Savia Capability Map (L1)
> 108 resources

- **archive-digest** (agent): >
- **contract-pin** (script): contract-pin.sh — SE-369 Contract Digest Pins
- **digest-extract** (script): digest-extract.sh — Capa 0 universal de extracción via markitdown (SE-172)
- **excel-digest** (agent): >
- **glm-compute-digest** (script): glm-compute-digest.sh — Computes SHA-256 of governance-layer-manifest.json
- **glm-verify** (script): glm-verify.sh — Verifies that manifest_digest.value matches computed SHA-256
- **inbox-check** (cmd): >
- **inbox-start** (cmd): >
- **kg-pipeline** (script): kg-pipeline.sh — Extract KG from digest output and persist to SaviaVaults
- **masked-digest** (script): masked-digest.sh — Masked digestion pipeline
- **meeting-confidentiality-judge** (agent): >
- **meeting-digest** (cmd): >
- **meeting-digest** (agent): >
- **meeting-risk-analyst** (agent): >
- **meeting-transcript-extract** (skill): Usar cuando se necesita extraer la transcripción de una reunión Teams desde el browser.
- **notify** (script): notify.sh — Cross-platform desktop notifications for Savia
- **org-meeting-capture** (skill): Captura de Conocimiento Tácito de Reunión: extrae decisores, acuerdos informales y señales políticas de transcripciones.
- **pdf-digest** (agent): >
- **pptx-digest** (agent): >
- **savia-announce** (cmd): >
- **savia-attest** (script): scripts/savia-attest.sh — SE-255 Slice 6
- **savia-backup** (script): Savia Backup & Restore Script
- **savia-board** (cmd): >
- **savia-bootstrap-log** (script): savia-bootstrap-log.sh — SPEC-CONSOLIDACION R3: log de instalación/arranque.
- **savia-branch** (script): savia-branch.sh — Git branch abstraction layer for Company Savia v3
- **savia-broadcast** (cmd): >
- **savia-compat** (script): savia-compat.sh — Portable helpers for cross-platform compatibility
- **savia-crypto** (script): savia-crypto.sh — RSA + AES hybrid encryption using openssl only
- **savia-crypto-ops** (script): savia-crypto-ops.sh — Encrypt and decrypt operations
- **savia-directory** (cmd): >
- **savia-double-optin-check** (script): savia-double-optin-check.sh — SPEC-186 (Era 199 Wave 1)
- **savia-dual** (cmd): Gestiona Savia Dual — inference sovereignty con failover entre Anthropic y gemma4 local
- **savia-dual** (skill): Usar cuando la inferencia cloud falla, es lenta o está rate-limited y se necesita failover local.
- **savia-enterprise** (script): savia-enterprise.sh — Enterprise module lifecycle manager
- **savia-env** (script): savia-env.sh — Provider-agnostic environment layer (SPEC-127 Slice 1)
- **savia-flow** (script): savia-flow.sh — Git-based project management: PBIs, sprints, boards via branch isolation
- **savia-flow-board** (script): savia-flow-board.sh — ASCII Kanban board renderer via branch isolation
- **savia-flow-ops** (script): savia-flow-ops.sh — CRUD operations for PBIs and assignments via branch isolation
- **savia-flow-practice** (skill): Usar cuando se implementa Savia Flow con dual-track y métricas de flujo en un proyecto.
- **savia-flow-sprint** (script): savia-flow-sprint.sh — Sprint lifecycle via branch isolation
- **savia-flow-tasks** (script): savia-flow-tasks.sh — Task management via branch isolation (PBI = task)
- **savia-flow-templates** (script): savia-flow-templates.sh — Project/team/member scaffolding via branch isolation
- **savia-flow-timesheet** (script): savia-flow-timesheet.sh — Time tracking via user branch
- **savia-forget** (cmd): >
- **savia-gallery** (cmd): Catálogo visual/interactivo de comandos, skills y agentes por rol y vertical
- **savia-goal** (cmd): Establece, gestiona y persigue objetivos persistentes cross-turn — equivalente Savia de /goal de Codex
- **savia-goal** (script): savia-goal.sh — Goal lifecycle management for Savia
- **savia-goals** (script): savia-goals.sh — Goals durables + heartbeats claimed-due (SE-347 lección PMA)
- **savia-hub-init** (script): savia-hub-init.sh — Inicializa el repositorio local de SaviaHub
- **savia-hub-sync** (skill): Usar cuando se sincroniza el repositorio SaviaHub con el workspace local.
- **savia-hub-sync** (script): savia-hub-sync.sh — status / push / pull / flight de SaviaHub (skill savia-hub-sync)
- **savia-identity** (skill): Usar al inicio de sesión para cargar la identidad completa y las reglas de comportamiento de Savia.
- **savia-ignore** (script): savia-ignore.sh — SE-218 S5: tool-specific exclusion layer
- **savia-inbox** (cmd): >
- **savia-index** (script): ── savia-index.sh ──────────────────────────────────────────────────────────
- **savia-index-rebuild** (script): ── savia-index-rebuild.sh ──────────────────────────────────────────────────
- **savia-install** (script): savia-install.sh — SPEC-CONSOLIDACION R4: bootstrap central idempotente.
- **savia-labs** (skill): Usar cuando se investiga, experimenta o audita epistemicamente. Triggers: 'investiga', 'experimento', 'hipotesis', 'preregistro', 'labs', 'divergencia', 'certificado de ignorancia', 'corpus de desconocidos', 'auditoria de reclutamiento', 'f
- **savia-live** (cmd): Show what Savia is working on right now — live task queue and recent activity
- **savia-memory** (skill): Usar cuando se lee, escribe, busca o consolida la memoria persistente entre sesiones de Savia.
- **savia-memory-bootstrap** (script): savia-memory-bootstrap.sh — crea store externo canónico ../.savia-memory/
- **savia-memory-mcp-stdio** (script): SPEC-141 · savia-memory MCP stdio wrapper
- **savia-memory-migrate** (script): savia-memory-migrate.sh — migra memoria de silos internos/externos al store canónico
- **savia-messaging** (script): savia-messaging.sh — Message creation, delivery, and inbox management
- **savia-messaging-actions** (script): savia-messaging-actions.sh — Announce, broadcast, and directory operations
- **savia-messaging-inbox** (script): savia-messaging-inbox.sh — Inbox, read, and reply operations
- **savia-messaging-privacy** (script): savia-messaging-privacy.sh — Subject sensitivity check
- **savia-orchestrator** (script): savia-orchestrator.sh — SCL-011: orquestador SAGI mínimo.
- **savia-orchestrator-helper** (script): savia-orchestrator-helper.sh — SPEC-127 Slice 4
- **savia-pbi** (cmd): >
- **savia-preferences** (script): savia-preferences.sh — manage ~/.savia/preferences.yaml (SPEC-127 Slice 1)
- **savia-quota-tracker** (script): savia-quota-tracker.sh — SPEC-127 Slice 5
- **savia-recall** (cmd): Recall and retrieve information from Savia memory
- **savia-reply** (cmd): >
- **savia-runs** (script): savia-runs.sh — SE-349: Agent Runs Operations Ledger (ARO)
- **savia-sandbox-doctor** (script): SPEC-149 -- savia-sandbox-doctor.sh
- **savia-school** (skill): Usar cuando el workspace se adapta para un entorno educativo con estudiantes menores de edad.
- **savia-school** (script): Savia School: Core educational vertical management library
- **savia-school-security** (script): Savia School Security Layer: Encryption, Access Control, GDPR
- **savia-send** (cmd): >
- **savia-setup** (cmd): >
- **savia-setup** (script): savia-setup.sh — SE-372: inicializador interactivo de configuracion completa.
- **savia-shield** (cmd): Gestión de Savia Shield: activar, desactivar y comprobar instalación del sistema de soberanía de datos. Desactivado por defecto.
- **savia-shield-check** (script): savia-shield-check.sh — SPEC-OC-01
- **savia-shield-setup** (script): savia-shield-setup.sh — Instalador de Savia Shield
- **savia-shield-status** (script): savia-shield-status.sh — Status determinístico de las 8 capas de Savia Shield
- **savia-skills** (script): savia-skills.sh — Unified skill management CLI (SE-277)
- **savia-sprint** (cmd): >
- **savia-status** (script): savia-status.sh — What is Savia doing right now?
- **savia-team** (cmd): >
- **savia-timesheet** (cmd): >
- **savia-trace** (script): savia-trace.sh — SE-313 S2: contexto distribuido de traza (W3C traceparent).
- **savia-travel** (script): savia-travel.sh — Travel Mode Core (≤150 lines)
- **savia-travel-init** (cmd): >
- **savia-travel-init** (script): savia-init.sh — Travel Mode Init Script (template)
- **savia-travel-ops** (script): savia-travel-ops.sh — Pack and init operations for savia-travel.sh
- **savia-travel-pack** (cmd): >
- **savia-vaults** (skill): Usar cuando se interactua con SaviaVaults — cupulas de contexto, busqueda federada, RAG hibrido (Savia RAG), servidores MCP/A2A, backups, confidencialidad. Triggers: 'crea una cupula', 'indexa documentacion', 'busca en los vaults', 'busqued
- **savia-voice-chunk** (script): savia-voice-chunk.sh — SE-075 Slice 2.
- **savia-voice-speak** (script): savia-voice-speak.sh — SE-075 Slice 3.
- **savia-watch** (script): savia-watch.sh — Live activity feed from Savia
- **savia-watchdog** (script): savia-watchdog.sh — Emergency fallback: detect internet loss, activate local LLM
- **savia-workspace** (script): savia-workspace.sh — SE-373: composicion de repos multi-repo para agentes.
- **transcriptor-digest** (skill): Usar cuando se detectan carpetas nuevas en el directorio de reuniones del transcriptor o se quiere digerir transcripciones y capturas de reuniones capturadas por Savia Sonora (ex-Savia Transcriptor). Triggers: digerir reuniones, transcripto
- **transcriptor-mark-digested** (script): transcriptor-mark-digested.sh — marcar una reunion como digerida
- **voice-inbox** (skill): Usar cuando se procesan mensajes de voz para transcribirlos y convertirlos en acciones.
- **word-digest** (agent): >
- **zeroclaw-meeting** (cmd): Live meeting transcription via ZeroClaw — speaker diarization, voice identification, and digest.
