# planning — Savia Capability Map (L1)
> 635 resources

- **/decide-architecture** (cmd): Clasifica una tarea como WORKFLOW (deterministica) o AGENT (loop). Bias hacia workflow per Anthropic. Sugiere plantilla inicial. Mide accuracy contra corpus curado de 20 tareas.
- **_template** (skill): TEMPLATE — copia este directorio para crear una skill nueva. NO se carga en runtime.
- **_template_python** (skill): TEMPLATE de skill Python-backed (SE-347/PMA). Usar cuando se copia este directorio para crear una skill que expone funcionalidad invocable con run(). NO se carga en runtime.
- **acceptance-cost** (script): acceptance-cost.sh — SE-360: costo por cambio aceptado (CLI wrapper).
- **accessibility-mode** (cmd): Toggle rápido de accesibilidad — activa, desactiva o muestra el estado
- **accessibility-setup** (cmd): Configura las preferencias de accesibilidad de Savia para adaptarse a tus necesidades
- **action-shape-classifier** (script): action-shape-classifier.sh — SE-273 S2: Guards de forma de acción
- **adaptive-halting** (script): adaptive-halting.sh — SE-074 Slice 1.5 — double-criterion halting check
- **adaptive-strategy-selector** (script): adaptive-strategy-selector.sh — Select loading strategy based on model tier
- **adb-run** (script): adb-run.sh — Execute adb-wrapper functions without compound && chains
- **add-maturity-levels** (script): add-maturity-levels.sh — Add maturity field to all skill frontmatter
- **ado-bridge** (script): ado-bridge.sh — Azure DevOps REST API v7.1 bridge for Savia PM commands
- **advisor-config** (script): advisor-config.sh — Generate Anthropic Advisor Strategy configuration
- **agents-catalog-sync** (script): agents-catalog-sync.sh — SE-047 Slice 1 agents catalog auto-sync.
- **agents-md-drift-check** (script): agents-md-drift-check.sh — SE-078
- **agents-md-generate** (script): agents-md-generate.sh — SE-078
- **agents-size-checker** (script): agents-size-checker.sh — SE-098: List agents by size, emit WARN/FAIL per Rule #22
- **ai-labor-impact** (skill): Usar cuando se analiza el impacto de la IA en el trabajo del equipo o la organización.
- **ai-model-card** (cmd): Genera model card documentando agentes IA, modelos, tareas y decisiones
- **always-on-install-cron** (script): always-on-install-cron.sh — Install scheduled monitoring detectors (SE-279 S3)
- **always-on-runner** (script): always-on-runner.sh — Scheduled Monitoring Detector Framework (SE-279)
- **architect** (agent): >
- **architecture-intelligence** (skill): Usar cuando se diseña o revisa la arquitectura de un proyecto nuevo o existente.
- **ast-comprehend** (script): ast-comprehend.sh — Extractor estructural multi-lenguaje (ast-comprehension skill)
- **ast-comprehension** (skill): Usar cuando se explora código desconocido y se necesita comprensión estructural sin leer ficheros enteros.
- **ast-quality-gate** (skill): Usar cuando se verifica la calidad de código generado por IA antes de merge.
- **attack-surface-map** (script): attack-surface-map.sh — SE-243 Attack Surface Mapping
- **attack-surface-mapper** (skill): Mapear la superficie de ataque de un dominio: subdominios, OSINT, typosquatting.
- **auto-loop-gate** (script): SE-230 Auto-Loop Gate — classifies requests into loop/single-shot/clarify
- **azdevops-queries** (script): =============================================================================
- **azure-devops-operator** (agent): >
- **azure-devops-queries** (skill): Usar cuando se necesitan consultas WIQL, actualización de work items o datos de sprint en Azure DevOps.
- **azure-pipelines** (skill): Usar cuando se gestiona o depura CI/CD con Azure Pipelines.
- **backlog-capture** (cmd): >
- **backlog-git** (cmd): Control de versiones para backlogs de proyectos
- **backlog-git-tracker** (skill): Usar cuando se capturan o comparan snapshots del backlog para detectar drift.
- **backlog-groom** (cmd): Grooming asistido — detectar items obsoletos, duplicados, sin criterios de aceptación
- **backlog-init** (script): backlog-init.sh — Initialize local backlog structure for a project
- **backlog-patterns** (cmd): Detecta PBIs duplicados o similares entre proyectos del portfolio
- **backlog-pbi-crud** (script): backlog-pbi-crud.sh — Create, read, update, archive PBIs in local backlog
- **backlog-prioritize** (cmd): Priorización automática RICE/WSJF con datos reales de esfuerzo y valor
- **backlog-query** (script): backlog-query.sh — Query local backlog PBIs by frontmatter fields
- **backlog-resolver** (script): backlog-resolver.sh — Resolve backlog data source (local-first, API fallback)
- **backlog-sync** (cmd): Sync local backlog with external PM tools (Azure DevOps, Jira, GitHub Issues)
- **backup** (cmd): Backup cifrado de perfiles, configuraciones y datos locales a NextCloud o Google Drive
- **backup** (script): backup.sh — Backup cifrado de datos locales a NextCloud/GDrive
- **banking-architecture** (skill): Usar cuando se diseña o revisa arquitectura para proyectos del sector bancario.
- **banking-bian** (cmd): Validar arquitectura contra estándar BIAN y generar diagramas ArchiMate
- **banking-detect** (cmd): Auto-detectar proyecto bancario por entidades BIAN, Kafka, Snowflake, SWIFT
- **banking-eda-validate** (cmd): Validar pipelines Kafka/EDA — topologías, schemas, DLQ, Saga, idempotencia
- **baseline-tighten** (script): baseline-tighten.sh — SE-046 Slice 1 baseline auto-tighten.
- **benchmark-hook-dispatch** (script): scripts/benchmark-hook-dispatch.sh — SE-253 Slice 4
- **bertopic-probe** (script): bertopic-probe.sh — SE-033 Slice 1 BERTopic viability probe.
- **board-flow** (cmd): Analiza el flujo de trabajo del board — WIP actual, cuellos de botella y métricas de flujo.
- **bus-factor-analysis** (skill): >
- **bus-factor-distribute** (script): bus-factor-distribute.sh -- Plan de knowledge transfer por developer objetivo.
- **bus-factor-scan** (script): bus-factor-scan.sh -- Wrapper orquestador para bus-factor-scan.py
- **business-analyst** (agent): >
- **calendar-deadlines** (cmd): Deadlines proximos con estado de preparacion — nada se queda atras
- **calendar-plan** (cmd): Planificar semana con focus blocks automaticos y priorizacion Eisenhower
- **calendar-rebalance** (cmd): Rebalancear focus blocks tras cambio de prioridades o calendario
- **calendar-sync** (cmd): Sincronizar calendario Outlook/Teams via Microsoft Graph API
- **calendar-today** (cmd): Vista del dia con alertas, reuniones, focus blocks y recomendaciones
- **calibration-judge** (agent): Truth Tribunal judge — confidence statements match evidence strength
- **capacity-forecast** (cmd): Previsión de capacidad a medio plazo — planifica recursos para los próximos 3-6 sprints
- **capacity-planning** (skill): Usar cuando se calcula la capacidad del equipo para un sprint o periodo.
- **capex-classify** (script): capex-classify.sh — SE-272 S1 CAPEX/OPEX classification
- **capex-evidence-package** (script): capex-evidence-package.sh — SE-272 S1 Evidence package generator
- **capex-phase-gate** (script): capex-phase-gate.sh — SE-272 S1 Phase gate recorder
- **case-init** (cmd): Scaffold a business case from pursuit and SOW data
- **case-kill-check** (cmd): Run valuation sentinel across all active cases for kill recommendations
- **case-validate** (script): case-validate.sh — SE-016: Validate business case directories
- **catalog** (cmd): Busca comandos en catálogo extendido por keyword o área
- **ceo-alerts** (cmd): Panel de alertas estratégicas para dirección — solo decisiones que requieren nivel C
- **ceremony-health** (cmd): Métricas de salud de ceremonias — duración, participación, resolution rate
- **changelog-assemble** (script): changelog-assemble.sh — Assemble CHANGELOG.md from CHANGELOG.d/ fragments
- **changelog-fragment** (script): changelog-fragment.sh — create a CHANGELOG fragment for the current PR
- **check-daemon-auth** (script): check-daemon-auth.sh
- **checkpoint** (script): SE-387 C/F4 — Durable orchestration checkpoint (local, ~/.savia/checkpoints/).
- **ci-duration** (script): ci-duration.sh — SE-361: mide duración de jobs de CI (wrapper).
- **ci-failure-tracker** (script): ci-failure-tracker.sh — Track CI pipeline failures for signal/noise analysis
- **ci-health** (cmd): Muestra tasa de fallo de pipelines CI a partir del log local de ejecuciones.
- **classifier-corpus-run** (script): classifier-corpus-run.sh — SE-314 AC-EV: regresión del corpus de clasificación.
- **classify-execution-level** (script): classify-execution-level.sh — Classify script by origin into execution tier
- **claude-md-drift-check** (script): claude-md-drift-check.sh — Valida que los conteos en CLAUDE.md coincidan con
- **client-profile** (cmd): Gestión de perfiles de cliente en SaviaHub
- **client-profile-manager** (skill): Usar cuando se crean, actualizan o consultan perfiles de cliente en SaviaHub.
- **cobol-developer** (agent): >
- **coherence-court** (script): coherence-court.sh — SE-350: Coherence Court (jueces transversales de consistencia entre etapas)
- **coherence-factual-judge** (agent): Coherence Court judge — stage output contradicts facts fixed in earlier stages
- **coherence-gates** (script): coherence-gates.sh — SE-377/380/381/383: gates de coherencia (advisory por defecto).
- **coherence-judge** (agent): Truth Tribunal judge — internal consistency (sums, dates, entities)
- **coherence-objectives-judge** (agent): Coherence Court judge — stage output contradicts declared objectives of the flow
- **coherence-premise-drift-judge** (agent): Coherence Court judge — silent premise drift between stages of a flow
- **coherence-scope-judge** (agent): Coherence Court judge — stage output violates scope/constraints fixed earlier
- **coherence-validator** (agent): >
- **commit-guardian** (agent): >
- **company-messaging** (skill): Usar cuando se envían mensajes internos cifrados entre miembros de la organización vía Company Savia.
- **company-repo** (cmd): >
- **company-repo** (script): company-repo.sh — Git operations for company repo lifecycle
- **company-repo-ops** (script): company-repo-ops.sh — Connect, status, and sync operations
- **company-repo-templates** (script): company-repo-templates.sh — Heredoc templates for company repo init
- **company-repo-templates-init** (script): company-repo-templates-init.sh — Heredoc templates for repo initialization
- **competence-score** (script): competence-score.sh — Calculate competence scores from tracking log
- **compile-agent-index** (script): compile-agent-index.sh — Compiled agent reference index for LLM routing
- **compress-skip-frozen** (script): compress-skip-frozen.sh — SE-029 Slice 3 frozen-core advisory.
- **confidence-calibrate** (script): confidence-calibrate.sh - Confidence Calibration Analytics
- **confidentiality-check** (script): confidentiality-check.sh — Verify project files comply with confidentiality levels
- **confidentiality-scan** (script): confidentiality-scan.sh — Scan for PII, credentials, real project names.
- **consensus-validation** (skill): Usar cuando una decisión técnica o recomendación necesita validación por panel de jueces.
- **containment-check** (script): containment-check.sh — Verify containment infrastructure is available
- **containment-run** (script): containment-run.sh — Execute command in proper containment level
- **content-fingerprint** (skill): Usar cuando se necesita un identificador corto, deterministico y reproducible derivado del contenido de una cadena o fichero — cache keys, ids de patrones, fingerprints de docs.
- **contract-check** (script): contract-check.sh — SE-386 S2: valida CapabilityDescriptors.
- **contribute** (script): contribute.sh — Capa de interacción con GitHub para comunidad
- **control-band-agent** (script): control-band-agent.sh — SE-357: invocación del agente por tier σ.
- **control-band-detect** (script): control-band-detect.sh — SE-357: detección determinista de control bands (sin LLM).
- **corporate-adopt** (script): corporate-adopt.sh — SE-271 S2
- **corporate-body-validate** (script): corporate-body-validate.sh — SE-271 S2
- **corporate-ledger-verify** (script): corporate-ledger-verify.sh — SE-271 S2
- **corporate-monotonicity-gate** (script): corporate-monotonicity-gate.sh — SE-271 S1
- **corporate-no-write-assert** (script): corporate-no-write-assert.sh — SE-271 S5: Assert no corp input → instance write
- **corporate/corporate-disconnect-drill** (script): corporate-disconnect-drill.sh — SE-271 S7 Disconnect Simulation Drill
- **corporate/corporate-resilience-check** (script): corporate-resilience-check.sh — SE-271 S7 Local Resilience Assessment
- **cost-center** (cmd): Cost management and billing — timesheets, budgets, forecasting, invoicing
- **cost-management** (skill): Usar cuando se gestionan timesheets, presupuestos, facturas o forecasting de costes.
- **count-commands** (script): count-commands.sh — SE-095: canonical counter for slash commands.
- **court-score-aggregator** (script): court-score-aggregator.sh
- **credential-egress** (script): credential-egress.sh — SE-353: resolución de credenciales SOLO en el punto de egress.
- **credential-proxy** (script): credential-proxy.sh — Managed Agents pattern: credential isolation
- **criterio-cite** (script): scripts/criterio-cite.sh — SE-255 Slice 5
- **criterio-init** (script): scripts/criterio-init.sh — SE-255 Slice 2
- **criterio-validate** (script): scripts/criterio-validate.sh — SE-257 Slice 1
- **criterion-simulation-judge** (agent): >
- **criticality** (script): criticality.sh — Dispatcher for criticality operations
- **criticality-assess** (cmd): Evaluar criticidad de un item con desglose de 5 dimensiones y perfil CoD
- **criticality-dashboard** (cmd): Vista cross-project de items criticos P0-P3 con heatmap por equipo
- **criticality-engine** (script): criticality-engine.sh — Operations: assess, dashboard, rebalance. Sourced by criticality.sh.
- **criticality-rebalance** (cmd): Redistribuir carga de trabajo del equipo respetando criticidad y capacidad
- **criticality-scoring** (script): criticality-scoring.sh — Pure scoring functions. Sourced by criticality-engine.sh.
- **daily-activation-plan** (script): daily-activation-plan.sh — SE-034: Daily Agent Activation Plan
- **daily-plan** (cmd): Generate or show today's agent activation plan with token budgets
- **daily-routine** (cmd): Rutina diaria adaptativa según el rol del usuario — Savia sugiere los comandos más relevantes para tu jornada
- **dependency-map** (cmd): >
- **dependency-scan** (script): dependency-scan.sh — Dependency Vulnerability Scanning con Trivy
- **dependency-scanner** (skill): Usar cuando se escanean vulnerabilidades en dependencias de proyectos (Node, Python, C#, Java, Go, Rust, Ruby) con Trivy fs. Genera SBOM CycloneDX.
- **detect-token-exhaustion** (script): detect-token-exhaustion.sh — SE-250: classify agent failure cause
- **developer-experience** (skill): Usar cuando se mide o mejora la experiencia de desarrollo del equipo.
- **devops-validation** (skill): Usar cuando se conecta un proyecto nuevo a Azure DevOps para validar su configuración Agile.
- **diagram-architect** (agent): >
- **diagram-generate** (cmd): >
- **diagram-generation** (skill): Usar cuando se necesita generar diagramas de arquitectura o flujo desde código o infraestructura.
- **diagram-import** (cmd): >
- **diagram-import** (skill): Usar cuando se importa un diagrama existente para extraer entidades y crear PBIs.
- **diagram-status** (cmd): >
- **doc-counts-check** (script): scripts/doc-counts-check.sh — SE-253 Slice 5
- **doc-quality-feedback** (skill): Usar cuando se recopila feedback de calidad de documentación tras usar skills y reglas.
- **dotnet-developer** (agent): >
- **dual-estimate** (script): dual-estimate.sh — Dual estimation engine: agent-time vs human-time
- **ecosystem-watcher** (skill): Usar una vez al mes para detectar cambios relevantes en el ecosistema de herramientas externas.
- **effect-reservation** (script): SE-387 C/F5 — Exactly-once effects: intent -> reservation -> gate -> execute -> receipt -> close.
- **egress-gate** (script): egress-gate.sh — SE-273 S3: Egress control gate
- **emergency-fallback** (script): emergency-fallback.sh — Operaciones PM sin LLM
- **emergency-mode** (cmd): Gestionar el modo emergencia con LLM local cuando el proveedor cloud no está disponible
- **emergency-mode** (skill): Usar cuando la API de Anthropic está caída y se necesita continuar operando con LocalAI.
- **emergency-plan** (script): emergency-plan.sh — Pre-descarga de Ollama y modelo LLM para modo offline
- **emergency-setup** (script): emergency-setup.sh — Setup rápido de LLM local para modo emergencia
- **emergency-status** (script): emergency-status.sh — Estado del sistema de emergencia PM-Workspace
- **emotional-state-tracker** (script): emotional-state-tracker.sh — Track session stress state for Savia
- **engagement-capacity-check** (script): engagement-capacity-check.sh — SE-271 S4: Capacity enforcement per engagement
- **engagement-init** (script): engagement-init.sh — SE-271 S3: Initialize client engagement with ethical walls
- **engagement-separation-proof** (script): engagement-separation-proof.sh — SE-271 S3: Generates verifiable separation proof
- **engagement-wall-check** (script): engagement-wall-check.sh — SE-271 S3: Cross-client isolation verification
- **ensure-daemons-auth** (script): ensure-daemons-auth.sh
- **enterprise-analytics** (skill): Usar cuando se necesitan métricas SPACE, aggregación de portfolio o forecasting empresarial.
- **enterprise-onboarding** (skill): Usar cuando se incorporan múltiples personas a la organización de forma masiva.
- **enterprise-reconcile** (script): enterprise-reconcile.sh — SE-271 S4: Classify enterprise scripts into wired/adapted/archived
- **enterprise/bench-match** (script): bench-match.sh — SE-022 Resource Bench Management
- **enterprise/bench-register** (script): bench-register.sh — SE-022 Resource Bench Management
- **enterprise/billing-milestone** (script): billing-milestone.sh — SE-018 Project Billing (IFRS 15)
- **enterprise/client-health-score** (script): client-health-score.sh — SE-024 Client Health Intelligence
- **enterprise/daily-activation-plan** (script): daily-activation-plan.sh — SE-034 Agent Activation Plan
- **enterprise/dep-graph** (script): dep-graph.sh — SE-020 Cross-Project Dependencies
- **enterprise/enterprise-migrate** (script): enterprise-migrate.sh — Unified migration command: Core -> Enterprise
- **enterprise/expertise-directory** (script): expertise-directory.sh — SE-023 Knowledge Federation
- **enterprise/knowledge-federator** (script): knowledge-federator.sh — SE-023 Knowledge Federation
- **enterprise/lessons-collector** (script): lessons-collector.sh — SE-032 Cross-Project Lessons Pipeline
- **enterprise/lessons-promote** (script): lessons-promote.sh — SE-032 Cross-Project Lessons Pipeline
- **enterprise/rbac-bulk-assign** (script): rbac-bulk-assign.sh — Bulk-assign roles from a CSV file
- **enterprise/rbac-check** (script): rbac-check.sh — Verify if a user has permission to run a command in a tenant
- **enterprise/release-create** (script): release-create.sh — SE-014 Release Orchestration
- **enterprise/release-gate-check** (script): release-gate-check.sh — SE-014 Release Orchestration
- **enterprise/rollback-module** (script): rollback-module.sh — Revert activation of an Enterprise module
- **enterprise/tenant-activate** (script): tenant-activate.sh — Activate multi-tenant mode in the workspace
- **enterprise/tenant-create** (script): tenant-create.sh — Create a new Savia Enterprise tenant
- **env-scrub** (script): env-scrub.sh — SE-326 S5: sanitiza el entorno antes de spawn.
- **eras-timeline-generate** (script): eras-timeline-generate.sh — Genera docs/eras-timeline.md desde ROADMAP.md
- **estimate-calibrate** (script): estimate-calibrate.sh — Recompute empirical agent speedups from actuals log
- **estimate-convert** (script): estimate-convert.sh — Convert human-days to agent-hours using dual ratios
- **eval-ablation-run** (script): eval-ablation-run.sh — SE-030-A
- **eval-output** (cmd): >
- **eval-workspace** (script): eval-workspace.sh — Evaluación integral de pm-workspace contra sala-reservas
- **evaluate-repo** (cmd): >
- **evaluations-framework** (skill): Usar cuando se diseñan o ejecutan evaluaciones de calidad de agentes y prompts.
- **evidence-capture** (script): evidence-capture.sh — SE-364: bucle de evidencia (wrapper CLI).
- **exchange-ledger** (script): exchange-ledger.sh — Federation exchange ledger (SE-263 S6)
- **execution-level-inventory** (script): execution-level-inventory.sh — Full inventory of scripts/hooks with execution levels
- **exit** (cmd): >
- **exit-dependencies-declare** (script): exit-dependencies-declare.sh — SE-272 S5: Declare exit package tool dependencies
- **exit-drill-execute** (script): exit-drill-execute.sh — SE-272 S5: Full exit drill simulation
- **exit-independence-verify** (script): exit-independence-verify.sh — SE-272 S5: Verify exit package independence
- **exit-package-generate** (script): exit-package-generate.sh — SE-272 S5: Per-engagement exit package generation
- **exit-purge-verify** (script): exit-purge-verify.sh — SE-272 S5: Verify purge after engagement forget
- **ext-platform-card-validate** (script): ext-platform-card-validate.sh — SE-272 Slice 4: Validate external platform card
- **ext-platform-export-gate** (script): ext-platform-export-gate.sh — SE-272 Slice 4: Export gate for external platforms
- **ext-platform-gate** (script): ext-platform-gate.sh — SE-272 Slice 4: Enforce asymmetry for external platforms
- **ext-platform-resilience** (script): ext-platform-resilience.sh — SE-272 Slice 4: Resilience for external platforms
- **factuality-judge** (agent): Truth Tribunal judge — factual accuracy of claims against verifiable sources
- **federation-discover** (script): federation-discover.sh — SCL-009: auto-descubrimiento de instancias federadas.
- **federation-drill** (script): federation-drill.sh — SE-263 S7: Compromised instance drill
- **flow-backlog-groom** (cmd): Review and prioritize backlog items
- **flow-burndown** (cmd): Show sprint burndown chart data
- **flow-metrics** (cmd): Dashboard de métricas de flujo Savia Flow (cycle time, lead time, throughput, CFR)
- **flow-spec-create** (cmd): Create a new SDD specification document
- **flow-sprint-board** (cmd): Display sprint board with task counts by column
- **flow-sprint-close** (cmd): Close sprint, move pending tasks to backlog, generate report
- **flow-sprint-create** (cmd): Create a new sprint with goal and dates
- **flow-task-assign** (cmd): Assign task to a team member
- **flow-task-create** (cmd): Create a new task in Savia Flow with frontmatter metadata
- **flow-task-move** (cmd): Move task between board columns (todo, in-progress, review, done)
- **flow-timesheet** (cmd): Log hours spent on a task
- **flow-timesheet-report** (cmd): Generate timesheet report for date range
- **flow-velocity** (cmd): Show historical velocity metrics
- **focal-checkin** (script): focal-checkin.sh — Check-in scheduling y señal de carga cognitiva (SE-230 Slice 3)
- **focal-dispatch** (script): focal-dispatch.sh — Prioriza y presenta la decisión humana más crítica (SE-230 Slice 2)
- **focal-status** (script): focal-status.sh — Vista agregada de nidos activos (SE-230 Slice 1)
- **focus-mode** (cmd): Modo single-task — carga una sola tarea y oculta distracciones
- **forge-idea** (cmd): Forja una idea mediante interrogatorio socratico con veredicto ternario ENDURECIDA/MAS_CLARA/MUERTA (SE-269 S1)
- **forge-idea** (script): forge-idea.sh — Presion socratica con veredicto ternario (SE-269 S1)
- **fork-agents** (script): fork-agents.sh — Lanza N invocaciones paralelas de Claude con prefijo cacheable
- **frontend-developer** (agent): >
- **frontend-probe** (script): frontend-probe.sh — SE-388 S1: detección de frontends y capability matrix.
- **frontier-strategy** (script): frontier-strategy.sh — SE-216 Slice 3: frontier selection strategies
- **gate-init** (script): scripts/gate-init.sh — SE-255
- **gate-post-receive** (script): scripts/gate-post-receive.sh — SE-255
- **gate-teardown** (script): scripts/gate-teardown.sh — SE-255
- **generate-capability-map** (script): ── generate-capability-map.sh — Thin wrapper around the Python generator.
- **generate-critical-facts** (script): scripts/generate-critical-facts.sh
- **generate-github-hooks** (script): generate-github-hooks.sh — SE-180
- **generate-index** (script): generate-index.sh — Generate discoverable index of all workspace components
- **git-history-secret-remediate** (script): SE-239 — Git history secret remediation helper
- **git-history-secret-scan** (script): SE-239 — Git history secret scanning
- **git-secret-scanner** (skill): Escanea el historial git o los commits pendientes de push buscando secrets con gitleaks. SE-239/SE-247.
- **go-developer** (agent): >
- **goal-service** (script): goal-service.sh — SE-326 S4: wrapper del goal service durable por sesión.
- **graph-query** (cmd): Consulta el grafo de conocimiento en lenguaje natural
- **graphrag-quality-gate** (script): graphrag-quality-gate.sh — SE-030-T
- **graphrag-quality-gates** (script): graphrag-quality-gates.sh — SE-030
- **grounding-verify** (script): SE-387 C/F2 — Grounding fail-closed (SE-383 lección).
- **guided-work** (cmd): Trabajo guiado — Savia te acompaña paso a paso con preguntas, adaptando el ritmo a tus necesidades
- **hallucination-fast-judge** (agent): Recommendation Tribunal judge — verifies that entities cited in a draft (files, functions, flags, libs, paths, commands) actually exist via tool calls
- **hallucination-judge** (agent): Truth Tribunal judge — detects invented facts via SelfCheck-style consistency
- **handback-resolve** (script): handback-resolve.sh — SE-332 Handback Obligation
- **hashline-edit** (script): hashline-edit.sh — Safe edit wrapper with stale-file protection (SE-149)
- **hashline-guard** (script): hashline-guard.sh — Stale-file protection for L3 agent edits (SE-149)
- **health-dashboard** (cmd): Dashboard de salud del proyecto unificado — Savia muestra una vista rápida adaptada al rol
- **heat-scheduler** (script): heat-scheduler.sh — Lightweight heat-based parallelism for dev sessions
- **help** (cmd): Catálogo de comandos y primeros pasos pendientes.
- **hook-assignment-rule** (script): hook-assignment-rule.sh — SE-270 Slice 5: hook vs documentation assignment rule.
- **hook-bench-all** (script): hook-bench-all.sh — SE-037 Slice 1 probe: measure latency of all hooks.
- **hook-latency-bench** (script): hook-latency-bench.sh — Mide la latencia media de cada hook registrado
- **hook-latency-budget** (script): hook-latency-budget.sh — SE-270 Slice 5: hook latency budget enforcement.
- **hook-pii-gate** (script): hook-pii-gate.sh — PII Quality Gate Pre-Commit Hook
- **hook-profile** (cmd): View or change the active SAVIA_HOOK_PROFILE (minimal/standard/strict/ci)
- **hook-profile** (script): hook-profile.sh — Get/set the active SAVIA_HOOK_PROFILE
- **hooks-integrity-check** (script): hooks-integrity-check.sh — SE-094: detect orphan and phantom hooks.
- **import-sprint-story** (cmd): >
- **incident-postmortem** (script): incident-postmortem.sh — SE-323 S4: rellena la plantilla de postmortem
- **incident-rca** (script): incident-rca.sh — SE-323 S2: harness de investigación de incidentes (RCA).
- **index-compact** (cmd): >
- **index-status** (cmd): >
- **infrastructure-agent** (agent): >
- **install-prepush-hook** (script): SE-247 — Instala el hook pre-push de seguridad en el repo actual o en uno dado.
- **install-savia-bridge-system** (script): install-savia-bridge-system.sh — Promote savia-bridge to a SYSTEM systemd unit.
- **install-watchdog** (script): install-watchdog.sh — Installs savia-watchdog as systemd service
- **instance-card** (script): instance-card.sh — Savia instance identity cards (SE-263 S2)
- **integration-status** (cmd): Dashboard de estado de todas las integraciones — APIs, webhooks, MCP, conectividad
- **java-developer** (agent): >
- **judge-anti-fatigue** (script): judge-anti-fatigue.sh — SE-273 S1: Anti-fatigue verdict tracking
- **judge-calibration** (script): judge-calibration.sh — FP/FN tracking para jueces adversariales (SE-269 S4)
- **judge-routing-verify** (script): judge-routing-verify.sh — SE-273 S1: CI parity check
- **judge-trigger-detector** (script): judge-trigger-detector.sh — SE-273 S1: Deterministic trigger detection
- **kg-cleanup** (script): kg-cleanup.sh — Archive orphaned/expired entities
- **kg-link-prediction** (script): kg-link-prediction.sh — SE-249: wrapper for kg-link-prediction.py
- **kg-query** (script): kg-query.sh — SE-218 S3: query KG con qualified names
- **kg-topology-analysis** (script): kg-topology-analysis.sh — SE-248: wrapper for kg-topology-analysis.py
- **knowledge-graph** (skill): Usar cuando se construye o consulta el grafo de conocimiento de entidades del proyecto.
- **knowledge-graph** (script): knowledge-graph.sh — SE-162: Shell wrapper for knowledge-graph.py
- **l13-meta-pruebas** (script): l13-meta-pruebas.sh — L13 F3: harness determinista de pruebas M1-M4.
- **l28-ablation** (script): l28-ablation.sh — L28-F1: prueba de ablacion del harness de Savia (sandbox).
- **labs-preregister** (script): labs-preregister.sh — Preregistro de hipotesis en Savia Labs
- **language-boundary-check** (script): scripts/language-boundary-check.sh — SE-253 Slice 7
- **law-check** (script): law-check.sh — SE-386 S1: valida Law Registry.
- **learning-autonomy** (script): learning-autonomy.sh — SCL-006: política de autonomía graduada por p_consistent
- **learning-divergence** (script): learning-divergence.sh — SCL-004 L1: divergencia grafo-modelo como instrumento
- **learning-federate** (script): learning-federate.sh — SCL-002/007: consume y comparte lecciones aprendidas
- **learning-guard** (script): learning-guard.sh — SCL-001 S4: guard de agnosticismo del bucle de aprendizaje
- **learning-lifecycle** (script): learning-lifecycle.sh — SCL-001 S2: sustrato como artefacto de despliegue
- **learning-persist** (script): learning-persist.sh — SCL-002: persiste una learning proposal en la cúpula
- **learning-proposal** (script): learning-proposal.sh — SCL-001 S1: canonical learning proposal capture
- **learning-reconcile** (script): learning-reconcile.sh — SCL-010: reconciliación de lecciones duplicadas/conflictivas.
- **learning-rollback** (script): learning-rollback.sh — SCL-001 S2: rollback instantáneo de una entrada del sustrato
- **legacy-assess** (cmd): >
- **legalize-es** (script): legalize-es.sh — Gestión del corpus legislativo español (legalize-es)
- **lesson-extract** (cmd): Extract a cross-project lesson from the current task
- **lesson-pipeline** (script): lesson-pipeline.sh — SE-032: Cross-Project Lessons Pipeline
- **lib/adb-wrapper** (script): ============================================================================
- **lib/concurrent-executor** (script): concurrent-executor.sh — Semaphore-bounded parallel task execution
- **lib/enterprise-helpers** (script): enterprise-helpers.sh — Sourceable helpers for Enterprise module checks
- **lib/llm-healer** (script): llm-healer.sh — SE-076 Slice 3
- **lib/mock-env** (script): mock-env.sh — Reusable mock environment library for pm-workspace scripts
- **lib/os-detect** (script): scripts/lib/os-detect.sh — Portable OS detection and path defaults
- **lib/slm-common** (script): slm-common.sh — Shared helpers for SLM subcommands (SE-049 Slice 1).
- **lightpanda-browser** (skill): DEPRECATED 2026-09-04 — sustituida por obscura-browser. No usar en casos nuevos. Se conserva como referencia histórica: Obscura gana en licencia (Apache-2.0 vs AGPL), telemetría (cero vs ON por defecto) y recursos (41MB RAM).
- **llms-txt-generate** (script): llms-txt-generate.sh — Genera docs/llms.txt y docs/llms-full.txt (SE-269 S5)
- **loop-budget-check** (script): scripts/loop-budget-check.sh
- **loop-run-log** (script): loop-run-log.sh — CLI para gestión del run-log append-only de skills autónomas
- **loop-state-init** (script): loop-state-init.sh — Inicializa STATE.md canónico para un skill autónomo
- **loop-state-prune** (script): loop-state-prune.sh — Archiva ítems cerrados en Recently Resolved
- **loop-verify** (script): loop-verify.sh — Genera prompt adversarial para sub-agente verificador (SE-228 S2)
- **managed-content** (skill): Usar cuando se regeneran secciones auto-generadas en documentos con marcadores de seguridad.
- **managed-scan** (cmd): Scan managed content for stale or outdated sections
- **managed-sync** (cmd): Synchronize and regenerate managed content markers
- **marketplace-publish** (cmd): Publish components to marketplace registry
- **mask-reversible** (script): mask-reversible.sh — SE-323 S1: reversible identifier masking for RCA.
- **masked-unmask** (script): masked-unmask.sh — Unmask a Claude response back to real entities
- **mcp-recommend** (cmd): >
- **measure-reliability** (script): measure-reliability.sh — Task consistency vs capability across repeated runs
- **memvid-backup** (skill): Usar cuando se crea un backup portable de la memoria externa de Savia.
- **meta-control** (script): meta-control.sh — L13 F2: control metacognitivo sobre el orquestador SAGI.
- **meta-monitor** (script): meta-monitor.sh — L13 F1: juicio metacognitivo de monitoreo.
- **meta-recalibra-ledger** (script): meta-recalibra-ledger.sh — L13 F4: recalibración desde señal real (ledger).
- **meta-recalibrate** (script): meta-recalibrate.sh — L13 F1: recalibración del juicio metacognitivo.
- **mind-virus/quarantine** (script): SE-345 — Mind Virus Defense: quarantine a malicious file (explicit flag only).
- **mobile-developer** (agent): >
- **model-capability-resolver** (script): model-capability-resolver.sh — Resolve model capabilities from YAML registry
- **my-sprint** (cmd): Vista personal del sprint — items asignados, progreso, cycle time, PRs pendientes
- **network-recon** (skill): Reconocimiento de red: port scan con nmap/RustScan + HTTP detection con httpx.
- **network-recon** (script): network-recon.sh — SE-246 Network Reconnaissance
- **nidos** (cmd): Manage parallel terminal isolation with named git worktrees (Savia Nidos)
- **nidos** (script): nidos.sh — Savia Nidos: parallel terminal isolation via named git worktrees
- **nidos-lib** (script): nidos-lib.sh — Shared utilities for Savia Nidos
- **nuclei-scanning** (skill): Usar cuando se escanean vulnerabilidades conocidas (CVEs, misconfigs) con Nuclei.
- **objective-contract** (script): objective-contract.sh — SE-273 S7: Objetivo delegado con antagonista obligatorio
- **obs-status** (cmd): Health check de todas las fuentes de observabilidad conectadas
- **obscura-browser** (skill): Navegador headless nativo de Savia para fetch/scrape (Rust, sin Chromium, 41MB RAM, sin telemetria). Usar cuando se navega a, se extrae contenido de, se scrapea, se renderiza JS, o se necesita CDP/MCP headless. NO para e2e (usar Playwright)
- **ollama-classify** (script): ollama-classify.sh — Clasificacion local de texto con Ollama
- **ollama-hardware-check** (script): ── ollama-hardware-check.sh ─────────────────────────────────────────────────
- **onboard** (cmd): >
- **onboard-enterprise** (cmd): Enterprise onboarding at scale — batch import, per-role checklists, knowledge transfer
- **onboarding-dev** (cmd): Technical onboarding with AI Buddy — auto-generates project docs, personalized plan, and 3-layer buddy agent
- **onboarding-dev** (skill): Usar cuando se incorpora un desarrollador nuevo al proyecto y necesita buddy IA.
- **operational-point-selector** (script): operational-point-selector.sh — SE-029 Slice 4.
- **operator-grant** (script): operator-grant.sh — Deterministic operator-grant ledger (SE-343)
- **opus47-calibration-scorecard** (script): opus47-calibration-scorecard.sh — SE-070 Slice 1
- **orchestration-protocol** (script): scripts/orchestration-protocol.sh — SE-205: typed inter-agent messaging
- **org-political-landscape** (skill): Análisis de Paisaje Político Interno: detecta tensiones, alianzas y centros de poder a partir de un mapa de stakeholders.
- **org-registrar** (script): org-registrar.sh — SE-365: CLI del grafo organizacional (wrapper).
- **org-stakeholder-mapper** (skill): Mapeador de Stakeholders y Decisores: extrae roles formales y reales, motivaciones, alianzas y tensiones de una organización.
- **orgchart-import** (cmd): >
- **orgchart-import** (skill): Usar cuando se importa un organigrama para extraer la estructura del equipo.
- **otel-emit** (script): otel-emit.sh — SE-313 S1: emisor de eventos de telemetría estándar.
- **oumi-probe** (script): oumi-probe.sh — SE-028 Slice 1 oumi integration viability probe.
- **output-compress** (script): output-compress.sh — Compress verbose tool output (stdin -> stdout)
- **overnight-roadmap-runner** (script): overnight-roadmap-runner.sh — wrapper del overnight-sprint-loop (SE-226)
- **overnight-sprint** (skill): Usar cuando se quiere ejecutar tareas de bajo riesgo de forma autónoma durante la noche.
- **overnight-sprint-loop** (script): scripts/overnight-sprint-loop.sh — SE-226: stateless overnight-sprint orchestrator
- **overnight-sprint-state** (script): scripts/overnight-sprint-state.sh — SE-226: stateless-session loop state management
- **parallel-dispatch** (skill): Usar cuando se necesitan subagentes en paralelo con admission-handle — lanza N tareas en background y recoge resultados después, sin bloquear el turno padre. Triggers: lanza subagentes en paralelo, paraleliza esto, admission-handle, recoge
- **parallel-dispatch** (script): parallel-dispatch.sh — Despacho paralelo con admission-handle (SE-347 lección PMA)
- **path-redact** (script): path-redact.sh — Redact absolute paths containing $HOME from text
- **pbi-decompose** (cmd): Decompose a PBI into granular technical tasks
- **pbi-decomposition** (skill): Usar cuando se descompone un PBI en tasks y se estiman las horas.
- **pbi-jtbd** (cmd): >
- **pbi-prd** (cmd): >
- **personal-vault** (skill): Usar cuando se lee o escribe el repositorio personal del usuario (perfil, preferencias, memoria).
- **php-developer** (agent): >
- **plan-diff-check** (script): plan-diff-check.sh — SE-358: verifica que el diff respeta el plan.md.
- **plugin-export** (cmd): Empaquetar pm-workspace como plugin distributable con validación de estructura
- **plugin-validate** (cmd): Validar estructura de plugin — skills, agents, commands e integridad
- **pm-backend-health** (script): pm-backend-health.sh — SE-092 MVP: detect PM backend configuration
- **poc-verify** (script): poc-verify.sh — SE-351: Verificador binario de PoCs (lección CyberGym)
- **pre-commit-sovereignty** (script): NOTE: -e omitted intentionally — grep returns 1 on no-match which would
- **pre-output-validator** (script): pre-output-validator.sh — TTSR-inspired pre-output rule validator (SE-150)
- **pre-tribunal-gates** (script): pre-tribunal-gates.sh — SE-251: deterministic pre-tribunal gates
- **prime-agent-eval-gate** (script): prime-agent-eval-gate.sh — SE-347 gate de arranque CRIT-001-strict
- **privacy-check-company** (script): privacy-check-company.sh — Privacy filter for company repo content
- **probe-devops** (script): probe-devops.sh — diagnóstico de acceso a Azure DevOps usando la
- **product-discovery** (skill): Usar antes de descomponer PBIs, cuando se necesita análisis JTBD y PRD del producto.
- **professional-domain** (skill): Family index for professional-domain skills (controlling, finance, labour, legal, sales). Load individual skills from subdirectories.
- **profile-discover** (script): profile-discover.sh — SE-219 S4: auto multi-profile discovery (abtop pattern)
- **profile-setup** (cmd): Savia te conoce — configuración del perfil en conversación natural.
- **profile-show** (cmd): Savia muestra tu perfil actual.
- **profile-switch** (cmd): Savia cambia de usuario — cambiar perfil activo.
- **project-activate** (cmd): Activa un proyecto como contexto activo en Savia: actualiza active-user.md y crea el directorio de memoria por proyecto si no existe. (SPEC-SE-093-ZERO-LEAK)
- **project-assign** (cmd): >
- **project-audit** (cmd): >
- **project-context** (script): project-context.sh — Project isolation for Savia (SE-093)
- **project-isolation-check** (script): project-isolation-check.sh — Verifica aislamiento de contexto por proyecto (SPEC-SE-093-ZERO-LEAK)
- **project-new** (cmd): >
- **project-release-plan** (cmd): >
- **project-roadmap** (cmd): >
- **project-switch** (cmd): Cambia el proyecto activo de Savia para aislamiento de contexto (SE-093).
- **project-update** (skill): Usar cuando se necesita una actualización integral del proyecto activo desde todas las fuentes.
- **project-update-devops** (script): project-update-devops.sh — wrapper que resuelve config real desde
- **prompt-optimizer** (skill): Usar cuando se optimiza el prompt de un skill o agente para mejorar su efectividad.
- **propuestas-index-gen** (script): propuestas-index-gen.sh — SE-222 S2: auto-generate INDEX.md for docs/propuestas/
- **protect-project-privacy** (script): protect-project-privacy.sh — Barrera de protección contra publicación accidental de proyectos
- **pursuit-bid** (cmd): Record bid/no-bid decision for a qualified pursuit
- **pursuit-close** (cmd): Close a pursuit as won or lost and trigger post-mortem analysis
- **pursuit-draft** (cmd): Generate proposal sections from library assets for a pursuit
- **pursuit-handoff** (cmd): Generate sales-to-delivery handoff package for a won pursuit
- **pursuit-init** (cmd): Scaffold a new pursuit opportunity directory with template files
- **pursuit-qualify** (cmd): Run BANT + MEDDIC qualification scoring on a pursuit
- **pursuit-validate** (script): pursuit-validate.sh — SE-015: Validate pursuit directories
- **push-pr** (script): push-pr.sh — CI + sign + push + create PR + release (zero re-sign commits)
- **python-developer** (agent): >
- **query-lib-index** (script): query-lib-index.sh — SE-031
- **query-lib-nl** (script): query-lib-nl.sh — SE-031 slice 2
- **query-lib-resolve** (script): query-lib-resolve.sh — SE-031
- **rbac-manager** (script): rbac-manager.sh — RBAC backend for Savia Enterprise multi-tenant
- **rca-eval-runner** (script): rca-eval-runner.sh — SE-323 S3: puntúa la suite sintética de RCA.
- **readiness-check** (script): readiness-check.sh — Deterministic capability checklist
- **recommendation-tribunal-orchestrator** (agent): Recommendation Tribunal orchestrator — 4 fast judges in parallel, aggregates scores, applies vetos, mutates output with banner. SYNC, <3s p95.
- **recover-savia** (script): recover-savia.sh — Launch a clean Claude session OUTSIDE pm-workspace
- **reflection-validation** (skill): Usar cuando una respuesta o decisión importante necesita validación metacognitiva (System 2).
- **reflection-validator** (agent): >
- **refresh-agent-maps** (script): refresh-agent-maps.sh
- **relacion-capture** (script): scripts/relacion-capture.sh — SE-255 Slice 3
- **relacion-detect-conflicts** (script): scripts/relacion-detect-conflicts.sh — SE-256 Slice 2
- **release-backfill** (script): release-backfill.sh — Create missing GitHub releases from git tags
- **release-invariants** (script): release-invariants.sh — SE-379: hace imposibles en CI las inconsistencias públicas básicas.
- **repos-list** (cmd): >
- **reranker** (skill): Usar cuando se recibe un top-K ruidoso de búsqueda en memoria y se necesita reordenar por relevancia.
- **reranker-probe** (script): reranker-probe.sh — SE-032 Slice 1 reranker viability probe.
- **resolve-all-open-prs** (script): resolve-all-open-prs.sh — one-shot helper that runs resolve-pr-conflicts.sh
- **resolve-pr-conflicts** (script): resolve-pr-conflicts.sh — auto-resolver for the recurring conflicts that
- **resolver-md-generate** (script): resolver-md-generate.sh — SE-160
- **resource-references** (skill): Usar cuando se necesitan referencias a recursos y plantillas del workspace.
- **restore-checkpoint** (script): restore-checkpoint.sh — Git stash checkpoint for high-radius operations
- **restore-drill** (script): restore-drill.sh — SE-258 Slice 2
- **roadmap** (script): roadmap.sh — SE-378: CLI del planning state machine.
- **robotica-diseno** (skill): Diseño profundo de robótica, automatización y hardware/software para el mundo físico. Usar cuando se diseña un robot, una celda de automatización, integración de sensores, servos, PLCs, visión artificial, o cuando se conecta un agente a har
- **rpi-start** (cmd): >
- **ruby-developer** (agent): >
- **rule-manifest-generate** (script): rule-manifest-generate.sh — Generador determinista de rule-manifest (SE-338)
- **rule-manifest-integrity** (script): rule-manifest-integrity.sh — SE-057 Slice 1 rule-manifest + INDEX integrity.
- **rule-usage-analyzer** (script): rule-usage-analyzer.sh — Analyze domain rule usage across the workspace
- **rule-violation-judge** (agent): Recommendation Tribunal judge — detects when a draft recommendation violates canonical rules (CLAUDE.md, autonomous-safety, radical-honesty, domain rules)
- **rules-index-generate** (script): rules-index-generate.sh — SE-097
- **run-adversarial-evals** (script): scripts/run-adversarial-evals.sh — SE-255 Slice 1
- **run-agent-evals** (script): run-agent-evals.sh — SE-204: evaluation harness for critical agents
- **rust-developer** (agent): >
- **sagi-e2e** (script): sagi-e2e.sh — SCL-013: flujo end-to-end (P6) — objetivo multi-paso sin
- **sagi-pruebas** (script): sagi-pruebas.sh — SCL-012: harness de pruebas P1-P5 del orquestador SAGI.
- **scale-optimizer** (cmd): Scaling optimization — analyze, benchmark, recommend improvements for growing organizations
- **scaling-operations** (skill): Usar cuando se analiza el tier de escala de un servicio o se necesitan optimizaciones de capacidad.
- **scheduled-messaging** (skill): Usar cuando se configuran mensajes automáticos programados a plataformas de comunicación.
- **school-analytics** (cmd): Teacher class-wide analytics and progress dashboard
- **school-diary** (cmd): Student learning diary and reflection journal
- **school-enroll** (cmd): Enroll student using alias (NO real names — privacy-first)
- **school-evaluate** (cmd): Teacher evaluates student project using encrypted rubric
- **school-export** (cmd): GDPR Article 15 — Export all student data in portable format
- **school-forget** (cmd): GDPR Article 17 — Right to Erasure, complete data deletion
- **school-portfolio** (cmd): Student portfolio view and learning journey showcase
- **school-progress** (cmd): View student progress and portfolio
- **school-project** (cmd): Student creates a new project from template
- **school-rubric** (cmd): Create or edit evaluation rubrics for grading
- **school-setup** (cmd): Configure classroom and initialize Savia School vertical
- **school-submit** (cmd): Student submits completed project for evaluation
- **score-diff** (cmd): >
- **scrapling-fetch** (script): scrapling-fetch.sh — SE-061 Slice 2 adaptive fetch wrapper.
- **scrapling-probe** (script): scrapling-probe.sh — SE-061 Slice 1 Scrapling viability probe.
- **setup-merge-drivers** (script): setup-merge-drivers.sh — configure local git with the custom merge drivers
- **setup-savia-dual** (script): setup-savia-dual.sh — Installer for Savia Dual (Linux/macOS)
- **setup-savia-remote** (script): setup-savia-remote.sh — Run ONCE on the remote server as root/sudo.
- **shield-ner-hook** (script): shield-ner-hook.sh — Savia Shield Capa 1.5: NER via daemon (fast)
- **skill-creator** (script): skill-creator.sh — SE-270 Slice 3 — Interactive skill scaffolding
- **skill-detect** (cmd): Detect repeated patterns and propose new skills automatically
- **skill-detect** (script): skill-detect.sh — SE-030: Skill Self-Improvement Pipeline
- **skill-eval** (cmd): >
- **skill-evaluation** (skill): Usar cuando se necesita seleccionar el skill más apropiado para una tarea dada.
- **skill-feedback-log** (script): skill-feedback-log.sh — Append skill invocation to JSONL log
- **skill-feedback-rank** (script): skill-feedback-rank.sh — Compute skill effectiveness and generate ranking
- **skill-keyword-detector** (script): skill-keyword-detector.sh — SE-203: detect which skills to auto-load based on keyword triggers
- **skill-layer-check** (script): skill-layer-check.sh — SE-356: validación de dos capas (core/peripheral) en skills.
- **skill-propose** (cmd): Proponer nuevo skill desde un workflow repetitivo — auto-genera scaffold si 3+ observaciones
- **skill-quality-eval** (script): skill-quality-eval.sh — Semantic skill quality evaluation via LLM judge (SE-278)
- **skill-quality-eval-all** (script): skill-quality-eval-all.sh — Batch evaluation of all skills (SE-278 S4)
- **skill-rank** (cmd): Show skill effectiveness ranking based on invocation data
- **skill-read** (cmd): Carga el contenido completo de un skill bajo demanda (progressive disclosure)
- **skill-routing-index** (script): skill-routing-index.sh — SE-152
- **skill-suggest** (script): skill-suggest.sh — Proactive skill suggestion hook (SE-276)
- **skills-collision-detect** (script): skills-collision-detect.sh — SE-270 Slice 1 — Skill description collision detection
- **skills-lock** (script): skills-lock.sh — SHA-256 integrity verification for skills
- **skills-md-generate** (script): Force C locale for deterministic sort + awk text handling across machines
- **skills-schema-generate** (script): skills-schema-generate.sh
- **skillssh-adapter** (script): ── skills.sh Adapter — Genera paquetes publicables para skills.sh ──
- **slm** (script): slm.sh — Unified SLM (Small Language Model) training toolchain dispatcher.
- **slm-data-collect** (script): slm-data-collect.sh — Collect training data from workspace artifacts.
- **slm-data-prep** (script): slm-data-prep.sh — Prepare project data for SLM fine-tuning
- **slm-dataset-prep** (script): slm-dataset-prep.sh — Phase 1 scaffolding for SLM training pipeline.
- **slm-dataset-validate** (script): slm-dataset-validate.sh — Validate a JSONL dataset before SLM training.
- **slm-eval-compare** (script): slm-eval-compare.sh — A/B compare eval results between 2 SLM versions.
- **slm-eval-harness-setup** (script): slm-eval-harness-setup.sh — Phase 5 scaffolding: eval config emission.
- **slm-export-gguf** (script): slm-export-gguf.sh — Generate llama.cpp conversion recipe for adapter→GGUF.
- **slm-modelfile-gen** (script): slm-modelfile-gen.sh — Generate Ollama Modelfile for a trained SLM.
- **slm-pipeline-validate** (script): slm-pipeline-validate.sh — Meta-validator for an SLM project directory.
- **slm-project-init** (script): slm-project-init.sh — Bootstrap a new SLM project with the canonical layout.
- **slm-synth** (script): slm-synth.sh — SE-028 slice 1
- **slm-synth-recipe** (script): slm-synth-recipe.sh — SE-028 Slice 1 scaffolding: emit oumi synth recipe YAML.
- **slm-train** (script): slm-train.sh — Fine-tune SLMs locally with Unsloth + export to Ollama
- **slm-train-config** (script): slm-train-config.sh — Phase 3 scaffolding: emit Unsloth/TRL YAML config.
- **smart-calendar** (skill): Usar cuando se gestiona la agenda inteligente con sincronización Outlook/Teams.
- **social-linkedin** (skill): >-
- **social-networks** (agent): >-
- **source-corroborator** (script): source-corroborator.sh — SE-273 S5: Corroboración de fuentes externas
- **sovereignty-benchmark** (script): sovereignty-benchmark.sh — Benchmark pm-workspace prompts with local LLM
- **sovereignty-classify** (script): sovereignty-classify.sh — SE-314: clasificador determinista de soberanía de datos.
- **sovereignty-decide** (script): sovereignty-decide.sh — SE-314 S2: decisión por umbral desde política YAML.
- **sovereignty-mask** (script): sovereignty-mask.sh — Wrapper for reversible data masking
- **sovereignty-ops** (script): sovereignty-ops.sh — Download operations for sovereignty-pack.sh
- **sovereignty-switch** (script): sovereignty-switch.sh — Switch between LLM providers for pm-workspace
- **sprint-autoplan** (cmd): Planificación inteligente de sprint — sugiere composición óptima desde backlog y capacidad
- **sprint-forecast** (cmd): Predicción de completitud del sprint basada en velocity histórica
- **sprint-management** (skill): Usar cuando se consulta el estado del sprint, se actualizan items o se genera el resumen.
- **sprint-plan** (cmd): Asiste en el Sprint Planning calculando capacity disponible y proponiendo la carga de trabajo.
- **sprint-release-notes** (cmd): >
- **sprint-retro** (cmd): Genera la plantilla de retrospectiva con datos del sprint para facilitar la ceremonia.
- **sprint-review** (cmd): Genera el resumen para la Sprint Review con todos los datos del sprint cerrado.
- **sprint-status** (cmd): Estado del sprint actual — progreso, burndown, alertas.
- **start-bridge** (script): start-bridge.sh — Invoked by Savia Claw remote_host.restart_bridge()
- **structural-framing-judge** (agent): Recommendation Tribunal judge — detects output with manual/protocol form over CBRN or sensitive domain
- **subagent-dispatch-gate** (script): subagent-dispatch-gate.sh — SE-313 S7c: gate de resolución de tiers + telemetría.
- **surface-map-authorize** (script): surface-map-authorize.sh — SE-243 Authorization helper
- **surrogate/router-check** (script): router-check.sh — wrapper SE-346: llm-router --check (read-only) con el python del venv.
- **sync-adapters/adapter-interface** (script): adapter-interface.sh — Common interface for backlog sync adapters
- **sync-adapters/azure-devops-adapter** (script): azure-devops-adapter.sh — Sync local backlog with Azure DevOps
- **sync-adapters/github-issues-adapter** (script): github-issues-adapter.sh — Sync local backlog with GitHub Issues
- **sync-adapters/jira-adapter** (script): jira-adapter.sh — Sync local backlog with Jira Cloud
- **sync-calendars** (cmd): Sincronizar disponibilidad entre calendarios de dos tenants Microsoft 365
- **sync-github-metadata** (script): sync-github-metadata.sh — Update GitHub repo metadata
- **sync-model-tiers** (script): sync-model-tiers.sh — Resolve abstract model tiers (heavy|mid|fast) to provider-
- **sync-tags-from-changelog** (script): sync-tags-from-changelog.sh — Create missing git tags from CHANGELOG.md
- **tabular-analyst** (agent): Analisis estadistico de datos tabulares. Usar PROACTIVELY cuando: se reciben datos en CSV, Excel, tablas markdown, o JSON arrays con >5 filas. Produce perfil estadistico y resumen para LLM.
- **tabular-intelligence** (skill): Usar cuando se analizan datos tabulares (CSV, Excel, tablas, metricas). Triggers: 'analiza esta tabla', 'metricas del sprint', 'tendencia de', 'distribucion de', 'correlacion entre', 'KPIs', 'datos financieros', 'perfil estadistico', 'resum
- **tabular-mcp-tool** (script): tabular-mcp-tool.sh — MCP tool: natural language query on tabular data
- **tabular-summarize** (script): tabular-summarize.sh — Detect + extract + summarize tabular data
- **task-create** (cmd): Add a task to Savia's todo list. Usage: /task-create Investigate this site...
- **task-decomposer** (script): task-decomposer.sh — Classify tasks as atomic/composite and decompose recursively
- **team-coordination** (skill): Usar cuando se coordinan múltiples equipos, se asignan miembros o se detectan bloqueantes cross-team.
- **team-evaluate** (cmd): >
- **team-onboarding** (cmd): >
- **team-onboarding** (skill): Usar cuando se incorpora un nuevo miembro al equipo y se evalúan sus competencias.
- **team-orchestrator** (cmd): Multi-team coordination — create teams, assign members, track cross-team dependencies and blockers
- **team-privacy-notice** (cmd): >
- **team-workload** (cmd): Muestra la carga de trabajo por persona — items asignados, horas remaining y balance de equipo.
- **tech-radar** (cmd): Radar tecnológico del proyecto — librerías, versiones, adopt/trial/hold/retire
- **tech-writer** (agent): >
- **telemetry-alert** (script): telemetry-alert.sh — SE-334 S2: emite alert cuando un issue cruza el umbral,
- **telemetry-issues** (script): telemetry-issues.sh — SE-334 S2: agrupa eventos por fingerprint en issues.
- **telemetry-tail-sample** (script): telemetry-tail-sample.sh — SE-313 S4: sampling tail + retención + rotación.
- **terminal-state-emit** (script): terminal-state-emit.sh — Emits structured termination reason for a loop/agent
- **terminal-state-read** (script): terminal-state-read.sh — Reads the last terminal state for a loop/agent
- **ternary-verdict** (script): ternary-verdict.sh — Unified data contract for ternary verdicts (SE-269 S2)
- **terraform-developer** (agent): >
- **tier3-probes** (skill): Usar cuando se valida la viabilidad de herramientas Tier 3 antes de adoptarlas en el workspace.
- **timeline-query** (script): timeline-query.sh — Query historical value of a field from bi-temporal timeline
- **token-estimator** (script): token-estimator.sh — Estimate token cost before execution
- **token-meter** (cmd): SE-326 S3: medición determinista de la superficie de la sesión (tokens heurísticos, baseline provider, snapshot inmutable)
- **tool-catalog** (cmd): Catálogo categorizado de herramientas (400+ comandos)
- **tool-result-trim** (script): tool-result-trim.sh — Deterministic hard cap for tool result output
- **topic-cluster** (skill): Usar cuando se agrupan retros, PBIs o incidentes en topics para detectar patrones transversales.
- **tracked-vs-nivel** (script): tracked-vs-nivel.sh — SE-258 Slice 1
- **trajectory-detector** (script): trajectory-detector.sh — SE-273 S6: Detección de desviación en minutos
- **transcriptor** (cmd): Gestionar Savia Transcriptor — escanear reuniones capturadas, digerir transcripciones y capturas, marcar como digeridas.
- **transcriptor-scan** (script): transcriptor-scan.sh — listar reuniones sin digerir de Savia Transcriptor
- **tribunal-critic** (script): tribunal-critic.sh — SE-201: quantitative scoring for tribunal verdicts
- **tribunal-status** (cmd): Show Truth Tribunal queue depth, recent verdicts, and pending evaluations
- **tribunal-tiered-runner** (script): tribunal-tiered-runner.sh — SE-106: Tiered tribunal execution
- **truth-tribunal-orchestrator** (agent): Truth Tribunal orchestrator — convenes 7 judges, aggregates scores, applies vetos, drives iteration
- **truth-tribunal-worker** (script): truth-tribunal-worker.sh — Consume queued Truth Tribunal verification
- **twin-decay-check** (script): twin-decay-check.sh — Escanea todos los twins y marca STALE los que superaron stale_after_days
- **typescript-developer** (agent): >
- **ua-bridge** (script): ua-bridge.sh — Bridge between Savia and Understand-Anything
- **ua-dashboard** (cmd): Start the interactive knowledge graph dashboard in browser
- **ua-install** (cmd): Install or update the Understand-Anything knowledge graph plugin
- **ua-install** (script): ua-install.sh — Install Understand-Anything plugin for Savia
- **unlimited-auth-detector** (script): unlimited-auth-detector.sh — SE-273 S4: Detecta delegación sin límite
- **update** (cmd): Comprobar y aplicar actualizaciones de pm-workspace desde GitHub, preservando datos locales
- **update** (script): update.sh — Sistema de actualización de pm-workspace
- **user-profile** (cmd): Gestiona perfiles de miembros del equipo — ver, crear o editar.
- **validate-agent-permissions** (script): validate-agent-permissions.sh — Verify agent permission_level matches tools
- **validate-changelog-links** (script): validate-changelog-links.sh — Verifica que cada ## [X.Y.Z] tiene su enlace [X.Y.Z]: URL
- **validate-ci-local** (script): ── validate-ci-local.sh — Parallel CI validation ────────────────────────
- **validate-commands** (script): ─────────────────────────────────────────────────────────────────────
- **validate-critical-facts-cap** (script): scripts/validate-critical-facts-cap.sh
- **validate-devops** (script): =============================================================================
- **validate-devops-checks** (script): shellcheck shell=bash
- **validate-filesize** (cmd): Validar que ficheros del workspace cumplen ≤150 líneas
- **validate-handoff** (script): SE-387 C/F3 — Handoff integrity.
- **validate-layer-contract** (script): validate-layer-contract.sh — SE-001 layer contract validator
- **validate-schema** (cmd): Validar schema de frontmatter y settings.json
- **validate-settings-local** (script): validate-settings-local.sh — Detect private/session data in settings.local.json
- **vault** (script): vault.sh — Personal Vault dispatcher (N3)
- **vault-graph** (cmd): SE-325: adyacencia inline + relaciones tipadas del knowledge graph de SaviaVaults (extract/validate/traverse/query)
- **vault-links** (script): vault-links.sh — SE-325: adyacencia inline + relaciones tipadas para SaviaVaults.
- **vault-ops** (script): vault-ops.sh — Personal Vault operations library (N3). Sourced by vault.sh.
- **vaults-backup-cron** (script): vaults-backup-cron.sh — Backup automático de las cúpulas SaviaVaults (CRIT-001).
- **vaults-export** (script): vaults-export.sh — Export vault with confidentiality filtering and signing
- **vaults-graph-query** (script): vaults-graph-query.sh — Knowledge graph queries via SaviaVaults
- **vaults-nextcloud-setup** (script): vaults-nextcloud-setup.sh — Configurar credenciales Nextcloud para backups
- **vaults-validate** (script): vaults-validate.sh — Validate documents against entity schemas
- **velocity-trend** (cmd): Tendencia de velocity con media móvil, detección de anomalías y factores explicativos
- **verdict-path** (script): verdict-path.sh — SE-367: wrapper de verdict-path.py (attach/expand/
- **verify-ledger-chain** (script): verify-ledger-chain.sh — SE-258 Slice 2
- **verify-principal** (script): scripts/verify-principal.sh — SE-256 Slice 3
- **vuln-scan** (script): vuln-scan.sh — Vulnerability scanner for pm-workspace scripts
- **wave-executor** (script): wave-executor.sh — Generic wave execution engine for DAG task graphs
- **wave-executor-lib** (script): wave-executor-lib.sh — Helper functions for wave-executor.sh
- **wellbeing-guardian** (cmd): Proactive individual wellbeing system — break reminders, after-hours alerts, work-life balance nudges
- **wellbeing-guardian** (skill): Usar cuando se monitorizan señales de bienestar individual en el equipo.
- **workspace-doctor** (cmd): >
- **workspace-health** (script): workspace-health.sh — Comprehensive health dashboard for pm-workspace
- **write-a-skill** (skill): Guia para crear una nueva skill correctamente en pm-workspace. Usar cuando una tarea se repite 2+ veces o tarda mas de 15 min.
