# quality — Savia Capability Map (L1)
> 267 resources

- **/speckit.analyze** (cmd): Alias spec-kit compatible. Review cruzado de una spec antes de implementar. Invoca skill consensus-validation. Compatible con github/spec-kit.
- **Coherence Court** (cmd): Audit consistency of a stage output against premises fixed in earlier stages of the same flow (SE-350)
- **Court Review** (cmd): Convene the Code Review Court to evaluate implementation quality across 6 judges
- **Failure Patterns** (cmd): List, show and resolve failure patterns from the Failure Pattern Memory store. Use when reviewing recurring agent errors, post-mortem analysis, or checking if an error has been seen before.
- **adversarial-containment** (script): adversarial-containment.sh — Adversarial test suite for containment
- **adversarial-security** (skill): Usar cuando se necesita auditar la seguridad de un proyecto con pipeline Red Team / Blue Team.
- **ai-exposure-audit** (cmd): Auditoría de exposición IA por rol — observed exposure, riesgo de desplazamiento, reskilling
- **android-autonomous-debugger** (skill): Usar cuando se depuran o testean apps Android contra dispositivos físicos via USB/ADB.
- **android-manifest-audit** (script): SE-240 — Android Manifest Audit
- **architectural-vocabulary-audit** (script): architectural-vocabulary-audit.sh — SE-082 Slice única.
- **architecture-judge** (agent): Code Review Court judge — boundaries, coupling, layer violations, patterns
- **attention-anchor-check** (script): attention-anchor-check.sh — SE-080 pattern coverage verifier
- **audit** (cmd): Generate professional executive audit report for workspace reliability assessment
- **automation-scheduler** (skill): Usar cuando se crean, gestionan o ejecutan automatizaciones programadas: morning briefs, weekly reports, PR stale checks, dependency scans, memory consolidation, drift audits. Triggers: programa una tarea, automatiza esto, crea una automati
- **banking-data-governance** (cmd): Auditar gobierno de datos — lineage, clasificación, GDPR/LOPD, feature stores
- **banking-mlops-audit** (cmd): Auditar pipeline MLOps — versionado, drift, XAI, model risk, scoring architectures
- **case-review** (cmd): Generate benefit realization review at 90/180/365 days
- **ci-bats-deps** (script): ci-bats-deps.sh — Generate dependency map for dynamic BATS test selection
- **ci-select-bats** (script): ci-select-bats.sh — Dynamic BATS test selector based on changed files
- **ci-test-quality-gate** (script): ci-test-quality-gate.sh — CI gate: test quality + coverage
- **codex-autonomy-canaries** (script): Contract tests plus real frontend probes. A policy-only PASS is not graduation.
- **cognitive-judge** (agent): Code Review Court judge — debuggability at 3AM, naming, complexity, logs
- **command-tier-audit** (script): scripts/command-tier-audit.sh — SE-253 Slice 1
- **comprehension-audit** (cmd): Scan recent implementations and identify which lack comprehension reports. Report coverage and recommendations.
- **confidentiality-auditor** (agent): Audita cumplimiento de confidencialidad en PRs de pm-workspace (repo publico). Descubre dinamicamente datos sensibles del workspace y verifica que no se filtran en el diff. Genera veredicto CLEAN/BLOCKED con firma si pasa.
- **confidentiality-sign** (script): confidentiality-sign.sh — Cryptographic signature for confidentiality audit
- **corporate-attest** (script): corporate-attest.sh — SE-271 S5: Generate signed corporate attestation
- **corporate-fleet-dashboard** (script): corporate-fleet-dashboard.sh — SE-271 S5: Derive fleet dashboard from attestations
- **corporate/corporate-attestation-queue** (script): corporate-attestation-queue.sh — SE-271 S7 Attestation Queue (Offline → Online)
- **corporate/engagement-audit-answer** (script): engagement-audit-answer.sh — SE-271 S6 Canonical Auditor Questions
- **correctness-judge** (agent): Code Review Court judge — logic, tests, edge cases, error paths
- **court-orchestrator** (agent): Convenes the Code Review Court, manages fix cycles, produces .review.crc
- **court-review** (script): court-review.sh — Code Review Court orchestration helper
- **court-turn-router** (script): court-turn-router.sh — SE-231 Adaptive Turn Routing for Code Review Court
- **coverage-report** (script): coverage-report.sh — Generate test coverage report for pm-workspace
- **decide-architecture-corpus-test** (script): decide-architecture-corpus-test.sh — SPEC-158
- **doc-health-audit** (script): doc-health-audit.sh — Documentation Health Auditor
- **docs-audit** (script): docs-audit.sh — Audita la estructura actual de docs/ y propone mejoras
- **docs-lint** (script): docs-lint.sh — SE-259 Slice 1. Bash wrapper for docs-lint.py
- **docs-quality-audit** (cmd): Auditar calidad de documentacion basada en feedback de agentes
- **drift-auditor** (agent): Auditoría de convergencia repo: detecta drift entre docs, config y código. Usar PROACTIVELY tras cambios grandes o al inicio de sprint.
- **dynamic-web-security-test** (script): dynamic-web-security-test.sh — SE-245 Dynamic Web Security Testing
- **dynamic-web-tester** (skill): Testing dinámico de endpoints web: XSS (DalFox), SQLi (sqlmap), Nuclei.
- **enterprise/activation-plan-review** (script): activation-plan-review.sh — SE-034 Agent Activation Plan
- **enterprise/audit-purge** (script): audit-purge.sh — SPEC-SE-037 Audit Log Retention Purge CLI
- **enterprise/audit-search** (script): audit-search.sh — SPEC-SE-037 Audit Log CLI Inspector
- **enterprise/governance-audit-trail** (script): governance-audit-trail.sh — SPEC-SE-006 Signed Audit Trail for Governance & Compliance
- **eval-lint** (script): eval-lint.sh — SE-316 S1: valida golden sets de tribunales (SE-274 S2).
- **evidence-first-development** (skill): Desarrollo evidence-first: rodea la implementación con un SPEC aprobado y un gauntlet de restricciones para que el line-by-line review sea opcional. Usar cuando se pide alta garantía (prove it works, no leeré el código), o en dominios de al
- **executive-audit** (script): executive-audit.sh — Executive Audit for PM Workspace
- **expertise-asymmetry-judge** (agent): Recommendation Tribunal judge — when draft falls in a domain the active user marks as `audit_level: blind`, force a rewrite with explanation/alternatives/verification
- **fix-assigner** (agent): Creates fix tasks from Court findings, assigns to dev agents, triggers re-review
- **fix-survival-check** (script): fix-survival-check.sh — SPEC-188 F4 — Weekly fix survival audit
- **focal-decisions-log** (script): focal-decisions-log.sh — Audit trail append-only de decisiones del director (SE-230 Slice 2)
- **frontend-test-runner** (agent): Post-commit frontend test execution — unit, component, e2e, coverage
- **grill-me** (skill): Adversarial review that hunts every weakness, assumption, edge case, and missing test. Opponent mode — finds what will break before it breaks in production. Use when merging, when reviewing security-critical code, or when the solution feels
- **guardrail-audit** (script): guardrail-audit.sh — SE-374: Auditoría de cumplimiento del principio Guardrail
- **guardrail-negative-tests** (script): guardrail-negative-tests.sh — SE-377 S1: negative tests para enforcement hooks.
- **hook-event-gap-audit** (script): hook-event-gap-audit.sh — Audita los 11 eventos de hook no cubiertos en pm-workspace
- **hook-injection-audit** (script): hook-injection-audit.sh — SE-060 Slice 1 hook injection patterns audit.
- **hook-latency-audit** (script): hook-latency-audit.sh — SE-037 Slice 1 hook latency enforcement audit.
- **hook-matcher-audit** (script): hook-matcher-audit.sh — SE-270 Slice 5: hook matcher specificity audit.
- **hook-test-coverage-audit** (script): hook-test-coverage-audit.sh — Detect hooks in .opencode/hooks/ without BATS tests.
- **hook-type-audit** (script): hook-type-audit.sh — SE-270 Slice 5: hook handler type audit.
- **hooks-coverage-matrix** (script): scripts/hooks-coverage-matrix.sh — SE-253 Slice 2
- **hub-audit** (cmd): Auditar dependencias entre reglas de dominio, comandos y agentes — recalcular el índice de hubs
- **iac-security-baseline** (script): iac-security-baseline.sh — Genera .trivyignore inicial para un proyecto legacy
- **iac-security-scan** (script): iac-security-scan.sh — IaC Security Scanning con Trivy
- **iac-security-scanner** (skill): Usar cuando se escanea IaC (Terraform, Bicep, Dockerfile, docker-compose) con Trivy config para detectar misconfiguraciones de seguridad antes del merge.
- **knowledge-lint** (cmd): Health check for the persistent knowledge base — detect orphans, stale refs, missing evidence
- **knowledge-lint** (script): knowledge-lint.sh — LLM Wiki pattern: periodic knowledge base health check
- **labs-self-audit** (script): labs-self-audit.sh — Comprobaciones de disciplina en Savia Labs
- **layer-baseline-test** (script): layer-baseline-test.sh — SE-348: criterion 7 (falsability) for coordination layers
- **legal-audit** (cmd): Auditoría de compliance legal contra legislación española (legalize-es)
- **legal-compliance** (skill): Usar cuando se audita compliance legal contra legislación española consolidada.
- **loop-phasing-audit** (script): loop-phasing-audit.sh — Audita el nivel loop_level declarado vs inferido
- **markdownlint** (script): Native markdownlint wrapper — no npm dependency.
- **mcp-audit** (script): mcp-audit.sh — audit MCP server token overhead across configs
- **mcp-security-audit** (script): mcp-security-audit.sh — SE-058 Slice 1 MCP supply-chain + config audit.
- **mobile-security-scan** (script): SE-240 — Mobile Security Scan
- **mobile-security-scanner** (skill): Usar cuando se escanea un APK/AAB Android en busca de vulnerabilidades de seguridad. Integra con MobSF (Docker) y análisis básico como fallback.
- **model-upgrade-audit** (cmd): Audit workspace components for prompt debt that newer models may not need
- **model-upgrade-audit** (skill): Usar cuando hay un modelo nuevo disponible y se quiere detectar prompt debt en el workspace.
- **model-upgrade-auditor** (agent): Audits agents, skills, and prompts for workarounds that newer models may no longer need. Proposes simplifications with eval-backed evidence.
- **mutation-audit** (skill): Usar cuando se quiere medir la calidad real de los tests mediante mutation testing.
- **mutation-audit** (script): mutation-audit.sh — SE-035 mutation testing audit.
- **opencode-cross-audit** (script): scripts/opencode-cross-audit.sh
- **opencode-parity-audit** (script): opencode-parity-audit.sh — SE-077 Slice 2
- **overnight-sprint** (cmd): Launch autonomous overnight sprint — executes low-risk tasks, creates PRs for human review
- **pentester** (agent): >
- **pentesting** (skill): Usar cuando se ejecuta un pentest contra una aplicación o infraestructura.
- **perf-audit** (cmd): Auditoría estática de rendimiento — detecta hotspots, async anti-patterns y funciones pesadas
- **perf-fix** (cmd): Optimización test-first de hallazgos de rendimiento — crea tests si no existen, aplica fix, re-verifica
- **perf-report** (cmd): Informe ejecutivo de rendimiento — hotspots, async issues, roadmap y tendencias
- **performance-audit** (skill): Usar cuando se audita el rendimiento estático de código para detectar hotspots.
- **permissions-wildcard-audit** (script): permissions-wildcard-audit.sh — SE-059 Slice 1 permissions wildcard audit.
- **pr-agent-judge** (skill): Usar cuando se añade pr-agent como juez externo en el Code Review Court.
- **pr-agent-judge** (agent): External 5th judge of the Code Review Court — wraps qodo-ai/pr-agent OSS (SPEC-124). Opt-in via COURT_INCLUDE_PR_AGENT=true.
- **pr-agent-run** (script): pr-agent-run.sh — SPEC-124
- **pr-context-loader** (script): pr-context-loader.sh — SPEC-022 F4: Load project context before PR creation
- **pr-digest** (cmd): Digestión contextual de un PR para revisión rápida. Analiza impacto, riesgos y genera resumen ejecutivo en español.
- **pr-pending** (cmd): >
- **pr-plan** (cmd): Pre-flight checklist: 15 gates (G0-G14) before push/PR. Prevents CI failures.
- **pr-plan** (script): pr-plan.sh — 10-gate pre-flight + sign + push + PR
- **pr-plan-gates** (script): pr-plan-gates.sh — Gate functions for pr-plan.sh (sourced, not executed)
- **pr-plan-queue-check** (script): pr-plan-queue-check.sh — SPEC-SE-012 Module 4.
- **pr-rebase** (script): pr-rebase.sh — Rebase current PR branch onto origin/main and re-sign.
- **pr-review** (cmd): >
- **pr-thermal-receipt** (script): pr-thermal-receipt.sh — Thermal receipt for PRs (CodeFlow-inspired)
- **pre-push-security-gate** (script): SE-247 — Pre-push security gate
- **prompt-security-scan** (script): prompt-security-scan.sh — Static analyzer for prompt injection/leakage
- **python-sbom** (script): python-sbom.sh — SE-056 Slice 1 Python SBOM + requirements audit.
- **rbac-management** (skill): Usar cuando se gestionan roles, permisos o se audita el acceso de usuarios.
- **rbac-manager** (cmd): Role-based access control — grant, revoke, audit roles and permissions
- **receipt-v2** (script): receipt-v2.sh — Content-bound review receipts (SE-260 S4)
- **recommendation-tribunal-search** (script): recommendation-tribunal-search.sh — SPEC-125 Slice 2: CLI for audit-trail inspection.
- **reconciler** (agent): Classifies contradictions into 3 buckets: evolution, auto-resolve, conflict-doc. Invoked by drift-auditor.
- **review-cache** (script): review-cache.sh - Gestión de caché de code review
- **review-cache-stats** (cmd): Estadísticas de la caché de code review
- **review-checkpoint** (cmd): Genera paquete de revision humana en 5 secciones: cambio, orden de lectura, hallazgos, verificacion manual, cierre (SE-269 S3)
- **review-checkpoint** (script): review-checkpoint.sh — Paquete de revision humana (SE-269 S3)
- **review-community** (script): review-community.sh — Revisión de PRs/issues de la comunidad (LOCAL ONLY)
- **review-depth-selector** (script): review-depth-selector.sh — Select review depth based on risk score
- **rule-orphan-detector** (script): rule-orphan-detector.sh — SE-048 Slice 1 rule usage audit.
- **sdd-research-lane** (script): sdd-research-lane.sh — SE-370: SDD Research lane — investigación auditable
- **security-attacker** (agent): >
- **security-audit-all** (script): security-audit-all.sh — Unified runner for all security scanners.
- **security-auditor** (agent): >
- **security-auto-remediation** (script): security-auto-remediation.sh — SPEC-070: Security Auto-Remediation PRs
- **security-benchmark-runner** (script): security-benchmark-runner.sh — SPEC-032 Security Benchmark Runner
- **security-defender** (agent): >
- **security-guardian** (agent): >
- **security-judge** (agent): Code Review Court judge — OWASP, PII, injection, auth, credentials
- **security-review** (cmd): >
- **security-scan** (script): security-scan.sh — Security audit for pm-workspace
- **self-audit** (script): self-audit.sh — SE-258 Slice 3
- **skill-audit** (script): skill-audit.sh — Baseline skill catalog quality auditor (SE-084 Slice 1)
- **skill-catalog-audit** (script): skill-catalog-audit.sh — SE-084 Slice 1.
- **skill-catalog-auditor** (script): skill-catalog-auditor.sh — SE-084 Slice 1 — Skill catalog quality auditor
- **skill-maturity-audit** (script): skill-maturity-audit.sh — SE-167 Skill Maturity Kanban
- **skills-depth-lint** (script): skills-depth-lint.sh — SE-270 Slice 2 — Single-level depth enforcement
- **skills-lint** (script): skills-lint.sh — SE-270 Slice 1 — Skill description routing rule validator
- **skills-overlap-audit** (script): skills-overlap-audit.sh — SE-270 Slice 3 — Skill description similarity matrix
- **skills-tier-audit** (script): skills-tier-audit.sh — SE-270 Slice 2 — Skill tier assignment audit
- **skills-usage-audit** (script): skills-usage-audit.sh — Audita uso de los 91 skills de pm-workspace.
- **sovereignty-audit** (cmd): Cognitive sovereignty audit — diagnose AI vendor lock-in risk and data portability
- **sovereignty-auditor** (skill): Usar cuando se audita el grado de dependencia cognitiva del equipo respecto a herramientas de IA.
- **spellcheck-docs** (script): spellcheck-docs.sh — Orthographic review using accent dictionaries
- **tabular-self-audit** (script): tabular-self-audit.sh — Post-turn: verify tabular tools were used when needed
- **tdd-vertical-slices** (skill): Test-driven development with vertical-slice red-green-refactor cycles. Use when applying TDD to a new feature or bug fix, when user mentions 'red-green-refactor', 'tdd', 'test-first', 'vertical slice' — explicitly avoids the 'horizontal sli
- **test-accessibility** (script): test-accessibility.sh — Validates accessibility universal feature files
- **test-ai-adoption** (script): ── test-ai-adoption.sh ────────────────────────────────────────────────────────
- **test-ai-governance** (script): ── test-ai-governance.sh ─────────────────────────────────────────────────────
- **test-ai-labor-impact** (script): test-ai-labor-impact.sh — Tests for AI Labor Impact Analysis (v2.5.0)
- **test-ai-planning** (script): ── test-ai-planning.sh ────────────────────────────────────────────────
- **test-ai-safety** (script): ── test-ai-safety.sh ────────────────────────────────────────────────────────
- **test-architect** (skill): Usar cuando se diseñan o generan tests de alta calidad en cualquier lenguaje.
- **test-architect** (agent): >
- **test-architecture-debt** (script): Test: Architecture & Debt v0.71.0 (Era 13)
- **test-auditor** (script): test-auditor.sh — Score, validate, and certify BATS test files
- **test-auditor-sweep** (script): test-auditor-sweep.sh — SE-039 Slice 1 global BATS test audit sweep.
- **test-backlog-git** (script): test-backlog-git.sh — Structural tests for BacklogGit (Era 32 — v2.7.0)
- **test-backlog-intelligence** (script): ── test-backlog-intelligence.sh ──────────────────────────────────────────────
- **test-backup** (script): test-backup.sh — Tests del sistema de backup cifrado
- **test-banking-vertical** (script): Test: v0.73.0 — Vertical Banking
- **test-ceo-reports** (script): ── test-ceo-reports.sh ───────────────────────────────────────────────────
- **test-ceremony-intelligence** (script): ── test-ceremony-intelligence.sh ────────────────────────────────────────────
- **test-client-profiles** (script): test-client-profiles.sh — Structural tests for Client Profiles (Era 31 — v2.6.0)
- **test-coherence-validator** (script): Test suite for Output Coherence Validator — Quality Validation Framework
- **test-company-profile** (script): ── test-company-profile.sh ──────────────────────────────────────────────────
- **test-company-repo** (script): test-company-repo.sh — Tests for Company Savia branch-based architecture
- **test-confidence-calibration** (script): Test suite for Confidence Calibration — Quality Validation Framework
- **test-consensus** (script): Test suite for Multi-Judge Consensus — Quality Validation Framework
- **test-context-aging** (script): ── test-context-aging.sh ──────────────────────────────────────────────────
- **test-context-eng-improvements** (script): test-context-eng-improvements.sh — Tests para Context Engineering Improvements
- **test-context-engineering** (script): Test Suite for Context Engineering 2.0 Commands (v0.62.0)
- **test-context-interview** (script): test-context-interview.sh — Structural tests for Context Interview (Era 33 — v2.8.0)
- **test-context-optimization** (script): Test: Context Optimization v0.71.0 (Era 13)
- **test-context-tracking** (script): ── test-context-tracking.sh ───────────────────────────────────────────────
- **test-contribute** (script): test-contribute.sh — Tests del sistema de comunidad y contribución
- **test-cost-center** (script): ── Test: cost-center (Era 38 — Cost Management & Billing) ──
- **test-coverage-checker** (script): test-coverage-checker.sh — Verify every script has a corresponding test
- **test-coverage-ratchet** (script): test-coverage-ratchet.sh — Ratchet no-decreciente de cobertura (SE-339)
- **test-cross-project** (script): ── test-cross-project.sh ────────────────────────────────────────────────
- **test-dev-productivity** (script): ── test-dev-productivity.sh ──────────────────────────────────────────────
- **test-docs-overhaul** (script): test-docs-overhaul.sh — Tests para Documentation Overhaul (Savia-led)
- **test-engineer** (agent): >
- **test-enterprise-dashboard** (script): ── Test: enterprise-dashboard (Era 41 — Enterprise Reporting & Analytics) ──
- **test-equality-shield** (script): test-equality-shield.sh — Tests for Equality Shield (v2.1.0)
- **test-era18-commands** (script): ── test-era18-commands.sh — Era 18 command structure validation ──
- **test-era18-formulas** (script): ── test-era18-formulas.sh — Scoring/formula correctness ──
- **test-era18-rules** (script): ── test-era18-rules.sh — Era 18 rule/config validation ──
- **test-evolving-playbooks** (script): Test Suite: Evolving Playbooks (ACE) — v0.63.0
- **test-frontend-testing** (script): test-frontend-testing.sh — Tests for Frontend Testing Nueva Era
- **test-governance** (script): Test: Governance v0.71.0 (Era 13)
- **test-governance-enterprise** (script): ── Test: governance-enterprise (Era 40 — Governance & Audit Trail) ──
- **test-hub-audit** (script): ── test-hub-audit.sh ─────────────────────────────────────────────────────
- **test-install** (script): test-install.sh — Structural validation for pm-workspace installers
- **test-integration-company** (script): test-integration-company.sh — Integration orchestrator for Savia v3
- **test-integration-hub** (script): ── test-integration-hub.sh ─────────────────────────────────────────────────
- **test-integrations-external** (script): Test: Integrations External v0.71.0 (Era 13)
- **test-memory-improvements** (script): Test suite for Memory Store Improvements v1.9.0
- **test-multi-layer-caching** (script): Test: Multi-Layer Caching — v0.65.0
- **test-multi-platform** (script): ── test-multi-platform.sh ──────────────────────────────────────────────────
- **test-multi-tenant** (script): Test Suite: v0.70.0 Multi-Tenant & Skills Marketplace
- **test-nl-resolution** (script): Test suite for NL Command Resolution v1.9.0
- **test-observability-core** (script): Test: Observability Core v0.71.0 (Era 13)
- **test-okr-strategy** (script): ── test-okr-strategy.sh ──────────────────────────────────────────────────────
- **test-onboard-enterprise** (script): ── Test: onboard-enterprise (Era 39 — Onboarding at Scale) ──
- **test-orgchart-diagrams** (script): ============================================================================
- **test-pbi-history** (script): test-pbi-history.sh — Validates PBI Field-Level History implementation
- **test-pbi-spec-links** (script): test-pbi-spec-links.sh — Tests for PBI ↔ Spec bidirectional linkage
- **test-performance-quality** (script): Test: Performance & Quality v0.71.0 (Era 13)
- **test-pipeline-devops** (script): Test: Pipeline & DevOps v0.71.0 (Era 13)
- **test-playbooks** (script): Test: Playbooks v0.71.0 (Era 13)
- **test-po-analytics** (script): ── test-po-analytics.sh ─────────────────────────────────────────────────
- **test-profile-system** (script): ── test-profile-system.sh ─────────────────────────────────────────────────
- **test-project-management** (script): Test: Project Management v0.71.0 (Era 13)
- **test-qa-toolkit** (script): ── test-qa-toolkit.sh ────────────────────────────────────────────────────
- **test-rbac-manager** (script): ── Test: rbac-manager (Era 37 — RBAC File-Based) ──
- **test-reflection-validator** (script): Test suite for Reflection Validator — System 2 Meta-Cognition Agent
- **test-repo-management** (script): Test: Repo Management v0.71.0 (Era 13)
- **test-review-community** (script): test-review-community.sh — Tests del protocolo de revisión comunitaria
- **test-runner** (agent): >
- **test-savia-confidentiality** (script): test-savia-confidentiality.sh — E2E encrypted messaging confidentiality
- **test-savia-crypto** (script): test-savia-crypto.sh — Tests for RSA+AES encryption
- **test-savia-flow** (script): test-savia-flow.sh — Tests for Savia Flow on branch-based architecture (~25 tests)
- **test-savia-flow-tasks** (script): test-savia-flow-tasks.sh — Git-native task tests via savia-branch.sh
- **test-savia-hub** (script): test-savia-hub.sh — Structural tests for SaviaHub (Era 30)
- **test-savia-index** (script): test-savia-index.sh — Tests for indexes on branch-based architecture
- **test-savia-messaging** (script): test-savia-messaging.sh — Tests for savia branch-based messaging infrastructure
- **test-savia-school** (script): test-savia-school.sh — Tests for Savia School educational vertical
- **test-savia-travel** (script): test-savia-travel.sh — Tests for Travel Mode (pack/unpack/verify/clean)
- **test-scale-optimizer** (script): ── Test: scale-optimizer (Era 42 — Scale & Integration Polish) ──
- **test-scoring-intelligence** (script): test-scoring-intelligence.sh — Tests for Scoring Intelligence (v2.3.0)
- **test-security-compliance** (script): Test: Security & Compliance v0.71.0 (Era 13)
- **test-semantic-memory** (script): Test suite for Semantic Memory 2.0 v0.64.0
- **test-sovereignty-audit** (script): test-sovereignty-audit.sh — Structural tests for Cognitive Sovereignty (Era 35 — v2.10.0)
- **test-specs-sdd** (script): Test: Specs & SDD v0.71.0 (Era 13)
- **test-stress-hooks** (script): ── test-stress-hooks.sh — Stress tests for all hooks ──
- **test-stress-runner** (script): ── test-stress-runner.sh — Orchestrator for all stress tests ──
- **test-stress-scripts** (script): ── test-stress-scripts.sh — Robustness of supporting scripts ──
- **test-stress-security** (script): ── test-stress-security.sh — Security pattern coverage (SEC-1 to SEC-9) ──
- **test-tasks-entities** (script): test-tasks-entities.sh — Validate Tasks as First-Class Entities
- **test-team-orchestrator** (script): ── Test: team-orchestrator (Era 36 — Multi-Team Coordination) ──
- **test-tech-lead** (script): ── test-tech-lead.sh ─────────────────────────────────────────────────────
- **test-update-system** (script): test-update-system.sh — Tests del sistema de actualización de pm-workspace
- **test-utils** (script): test-utils.sh — Funciones compartidas para todos los test scripts
- **test-vertical-compliance** (script): ── test-vertical-compliance.sh ────────────────────────────────────────────────
- **test-vertical-detection** (script): test-vertical-detection.sh — Tests del sistema de detección de verticales
- **test-verticals** (script): Test: Verticals v0.71.0 (Era 13)
- **test-wellbeing-guardian** (script): test-wellbeing-guardian.sh — Structural tests for Wellbeing Guardian (Era 34 — v2.9.0)
- **test-workspace** (script): test-workspace.sh — wrapper SE-253 Slice 7
- **tests/test-adb-wrapper** (script): ============================================================================
- **tls-security-check** (script): SE-242 — TLS Security Check
- **tls-security-checker** (skill): Usar cuando se verifica TLS/SSL o security headers HTTP de un servidor web. Invocable pre-deploy o en auditorías periódicas.
- **tool-ergonomics-audit** (script): tool-ergonomics-audit.sh — SPEC-160: Tool Ergonomics Auto-Audit
- **turn-sdlc-audit** (script): turn-sdlc-audit.sh — SE-336 S1: auditor Turn-SDLC
- **twin-linter** (script): twin-linter.sh — Valida twin.md contra schema SPEC-169
- **verification-lattice** (skill): Usar cuando se necesita verificación multi-capa más allá del code review estándar.
- **visual-diff-merge-check** (script): scripts/visual-diff-merge-check.sh — SPEC-046: Visual Diff QA at Merge Time
- **visual-digest** (agent): Digestión de imágenes con OCR contextual — 5 pasadas. Fotos de pizarras, notas manuscritas, diagramas en papel, capturas de reuniones. Usa contexto REAL del proyecto para resolver ambigüedades. PROACTIVELY cuando se detectan imágenes en car
- **visual-qa-agent** (agent): Visual QA: screenshot analysis, wireframe comparison, regression detection. Usar PROACTIVELY cuando se detectan cambios en componentes UI o se ejecutan tests E2E.
- **web-e2e-tester** (agent): Autonomous E2E testing of web apps against live instances. Use PROACTIVELY when: deploying savia-web, after UI changes, or running regression tests. Equivalent of android-autonomous-debugger for web.
- **web-headers-check** (script): SE-242 — Web Security Headers Check
- **workspace-integrity** (skill): Usar cuando se audita la integridad del workspace (drift, reglas, agentes, baseline).
- **zeroclaw** (cmd): Interface with ZeroClaw ESP32 — setup, test, send commands, flash firmware.
